/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    api: {
      Account: () => import('#transport/account/controllers/api/account_controller'),
      Preferences: () => import('#transport/account/controllers/api/preferences_controller'),
      Profile: () => import('#transport/account/controllers/api/profile_controller'),
    },
  },
  auth: {
    api: {
      AcceptInvitation: () => import('#transport/auth/controllers/api/accept_invitation_controller'),
      EmailVerification: () => import('#transport/auth/controllers/api/email_verification_controller'),
      ForgotPassword: () => import('#transport/auth/controllers/api/forgot_password_controller'),
      Login: () => import('#transport/auth/controllers/api/login_controller'),
      Logout: () => import('#transport/auth/controllers/api/logout_controller'),
      Me: () => import('#transport/auth/controllers/api/me_controller'),
      Register: () => import('#transport/auth/controllers/api/register_controller'),
      ResetPassword: () => import('#transport/auth/controllers/api/reset_password_controller'),
      SocialApi: () => import('#transport/auth/controllers/api/social_api_controller'),
    },
  },
  core: {
    api: {
      DashboardApi: () => import('#transport/core/controllers/api/dashboard_api_controller'),
      MaintenanceApi: () => import('#transport/core/controllers/api/maintenance_api_controller'),
    },
    Health: () => import('#transport/core/controllers/health_controller'),
  },
  file: {
    api: {
      File: () => import('#transport/file/controllers/api/file_controller'),
      FilesAltApi: () => import('#transport/file/controllers/api/files_alt_api_controller'),
      FilesApi: () => import('#transport/file/controllers/api/files_api_controller'),
      FilesDeleteApi: () => import('#transport/file/controllers/api/files_delete_api_controller'),
      FilesShowApi: () => import('#transport/file/controllers/api/files_show_api_controller'),
      FilesUploadApi: () => import('#transport/file/controllers/api/files_upload_api_controller'),
      FoldersApi: () => import('#transport/file/controllers/api/folders_api_controller'),
      FoldersDeleteApi: () => import('#transport/file/controllers/api/folders_delete_api_controller'),
      FoldersShowApi: () => import('#transport/file/controllers/api/folders_show_api_controller'),
      FoldersUpdateApi: () => import('#transport/file/controllers/api/folders_update_api_controller'),
    },
  },
  identity: {
    api: {
      PermissionsApi: () => import('#transport/identity/controllers/api/permissions_api_controller'),
      RolesApi: () => import('#transport/identity/controllers/api/roles_api_controller'),
      RolesCreateApi: () => import('#transport/identity/controllers/api/roles_create_api_controller'),
      RolesDeleteApi: () => import('#transport/identity/controllers/api/roles_delete_api_controller'),
      RolesShowApi: () => import('#transport/identity/controllers/api/roles_show_api_controller'),
      RolesUpdateApi: () => import('#transport/identity/controllers/api/roles_update_api_controller'),
      UsersApi: () => import('#transport/identity/controllers/api/users_api_controller'),
      UsersCreateApi: () => import('#transport/identity/controllers/api/users_create_api_controller'),
      UsersDeleteApi: () => import('#transport/identity/controllers/api/users_delete_api_controller'),
      UsersShowApi: () => import('#transport/identity/controllers/api/users_show_api_controller'),
      UsersUpdateApi: () => import('#transport/identity/controllers/api/users_update_api_controller'),
    },
  },
  log: {
    api: {
      LogsApi: () => import('#transport/log/controllers/api/logs_api_controller'),
    },
  },
}
