/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import PageContactFormSubmitted from '#events/page/contact_form_submitted'

export const events = {
  page: {
    ContactFormSubmitted: PageContactFormSubmitted,
  },
}
