/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  page: {
    SendContactFormEmail: () => import('#listeners/page/send_contact_form_email'),
  },
}
