/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    front: {
      Account: () => import('#controllers/account/front/account_controller'),
      EmailChange: () => import('#controllers/account/front/email_change_controller'),
    },
  },
  auth: {
    admin: {
      Permissions: () => import('#controllers/auth/admin/permissions_controller'),
      PermissionsCreate: () => import('#controllers/auth/admin/permissions_create_controller'),
      PermissionsUpdate: () => import('#controllers/auth/admin/permissions_update_controller'),
      Roles: () => import('#controllers/auth/admin/roles_controller'),
      RolesCreate: () => import('#controllers/auth/admin/roles_create_controller'),
      RolesShow: () => import('#controllers/auth/admin/roles_show_controller'),
      RolesUpdate: () => import('#controllers/auth/admin/roles_update_controller'),
      Users: () => import('#controllers/auth/admin/users_controller'),
      UsersCreate: () => import('#controllers/auth/admin/users_create_controller'),
      UsersShow: () => import('#controllers/auth/admin/users_show_controller'),
      UsersUpdate: () => import('#controllers/auth/admin/users_update_controller'),
    },
    api: {
      Me: () => import('#controllers/auth/api/me_controller'),
      Token: () => import('#controllers/auth/api/token_controller'),
      UsersApi: () => import('#controllers/auth/api/users_api_controller'),
      UsersCreateApi: () => import('#controllers/auth/api/users_create_api_controller'),
      UsersDeleteApi: () => import('#controllers/auth/api/users_delete_api_controller'),
      UsersShowApi: () => import('#controllers/auth/api/users_show_api_controller'),
      UsersUpdateApi: () => import('#controllers/auth/api/users_update_api_controller'),
    },
    front: {
      AcceptInvitation: () => import('#controllers/auth/front/accept_invitation_controller'),
      EmailVerification: () => import('#controllers/auth/front/email_verification_controller'),
      ForgotPassword: () => import('#controllers/auth/front/forgot_password_controller'),
      Register: () => import('#controllers/auth/front/register_controller'),
      ResetPassword: () => import('#controllers/auth/front/reset_password_controller'),
      Session: () => import('#controllers/auth/front/session_controller'),
      Social: () => import('#controllers/auth/front/social_controller'),
    },
  },
  core: {
    admin: {
      Dashboard: () => import('#controllers/core/admin/dashboard_controller'),
    },
    front: {
      Home: () => import('#controllers/core/front/home_controller'),
      Robots: () => import('#controllers/core/front/robots_controller'),
      Sitemap: () => import('#controllers/core/front/sitemap_controller'),
    },
  },
  file: {
    admin: {
      FileFolders: () => import('#controllers/file/admin/file_folders_controller'),
      Files: () => import('#controllers/file/admin/files_controller'),
    },
    api: {
      File: () => import('#controllers/file/api/file_controller'),
    },
  },
  health: {
    Health: () => import('#controllers/health/health_controller'),
  },
  log: {
    admin: {
      Logs: () => import('#controllers/log/admin/logs_controller'),
    },
  },
  maintenance: {
    admin: {
      Maintenance: () => import('#controllers/maintenance/admin/maintenance_controller'),
    },
  },
  page: {
    admin: {
      PageRevisions: () => import('#controllers/page/admin/page_revisions_controller'),
      PageTranslations: () => import('#controllers/page/admin/page_translations_controller'),
      Pages: () => import('#controllers/page/admin/pages_controller'),
      PagesCreate: () => import('#controllers/page/admin/pages_create_controller'),
      PagesPreview: () => import('#controllers/page/admin/pages_preview_controller'),
      PagesShow: () => import('#controllers/page/admin/pages_show_controller'),
      PagesUpdate: () => import('#controllers/page/admin/pages_update_controller'),
    },
    api: {
      BuilderOperations: () => import('#controllers/page/api/builder_operations_controller'),
    },
    front: {
      Contact: () => import('#controllers/page/front/contact_controller'),
      Page: () => import('#controllers/page/front/page_controller'),
    },
  },
  preferences: {
    api: {
      Theme: () => import('#controllers/preferences/api/theme_controller'),
    },
    front: {
      Preferences: () => import('#controllers/preferences/front/preferences_controller'),
    },
  },
  profile: {
    front: {
      Profile: () => import('#controllers/profile/front/profile_controller'),
    },
  },
  template: {
    admin: {
      Templates: () => import('#controllers/template/admin/templates_controller'),
      TemplatesPreview: () => import('#controllers/template/admin/templates_preview_controller'),
    },
    api: {
      Templates: () => import('#controllers/template/api/templates_controller'),
    },
  },
}
