/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import AuthForgotPassword from '#events/auth/forgot_password'
import AuthUserRegistered from '#events/auth/user_registered'

export const events = {
  auth: {
    ForgotPassword: AuthForgotPassword,
    UserRegistered: AuthUserRegistered,
  },
}
