/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  auth: {
    SendForgotPasswordEmail: () => import('#listeners/auth/send_forgot_password_email'),
    SendVerificationEmail: () => import('#listeners/auth/send_verification_email'),
  },
}
