/**
 * `api` flavor manifest.
 *
 * Derives the headless REST flavor from `main`: prunes the entire Inertia/Vite
 * view layer (the `inertia/` tree, providers, configs, asset tooling and every
 * session-rendered controller), the public site surface (home, sitemap,
 * robots, contact) AND the whole CMS module (page/template/builder + Transmit)
 * — the CMS lives on `main` only. What remains is a pure token-guarded REST
 * backend.
 *
 * Everything the flavor keeps is reachable through the versioned REST layer
 * (`/api/v1/*`, issue #7) behind the API token guard (#6):
 * - the non-CMS domain layer (models, migrations, repositories, services,
 *   actions, transformers, validators) — auth, files, logs, maintenance;
 * - `@adonisjs/drive` with public file serving, Redis, mail, i18n, the rate
 *   limiter, shield and a first-class env-driven CORS policy.
 *
 * Because the CMS is pruned, this manifest reuses the `inertia` flavor's CMS
 * delete inventory (module, controllers, transformers, events, listeners,
 * mails, migrations, seeders, i18n, preview-token helper, Transmit) and its
 * composition rewrites (`start/routes.ts`, events, nav, dashboard, sitemap,
 * container, `config/shield.ts`, `config/database.ts`).
 *
 * Per the "variation only in config/composition/docs files" rule, the
 * rewrite set is exactly the allowlisted composition files: the route module
 * index, feature flags, CORS, the view-layer asset middleware seam, the
 * boot/serve assembly (`adonisrc.ts`), environment validation, the env
 * template, `package.json`, `tsconfig.json` and the README. The `package.json`
 * rewrite carries the script and import-map adjustments; the frontend and
 * Transmit dependencies are then pruned by name through the manifest's
 * `dependencies` field, exactly like the `inertia` flavor. Any coupling
 * discovered between kept code and the pruned view/CMS layer while
 * implementing was resolved by refactoring `main`, never by patching this
 * manifest.
 *
 * The auth endpoints (`/api/v1/auth`) and the admin REST surface
 * (`/api/v1/admin`) are exactly the non-CMS ones built on `main` in #6 and #7
 * — this flavor adds no endpoints, it only removes the view layer and the
 * CMS.
 *
 * Applied by {@link '../engine'} via
 * `node --import @poppinss/ts-exec tooling/prune/apply.ts api`.
 */
import type { FlavorManifest } from '#prune/types'

const apiManifest: FlavorManifest = {
  flavor: 'api',

  delete: [
    // ─── Frontend tree (Inertia/React/Vite/Tailwind) ─────────────────────
    'inertia',
    'tsconfig.inertia.json',
    'vite.config.ts',
    'vitest.config.ts',
    'config/inertia.ts',
    'config/vite.ts',

    // ─── View-layer server middleware ────────────────────────────────────
    'app/http/middleware/core/inertia_middleware.ts',

    // ─── Page transport adapter — Inertia-dependent half of the REST ──────
    // ─── contract. rest_resource.ts stays (transport-agnostic); only this ──
    // ─── pipeline and its unit tests need the pruned Inertia binding. ──────
    'app/http/rest/page_resource.ts',

    // ─── Session-rendered front controllers ──────────────────────────────
    // front = guest/public pages (auth, self-service, home, sitemap, robots).
    'app/http/controllers/auth/front',
    'app/http/controllers/account/front',
    'app/http/controllers/profile/front',
    'app/http/controllers/preferences/front',
    'app/http/controllers/core/front',

    // ─── Session-guarded Inertia admin controllers ───────────────────────
    'app/http/controllers/auth/admin',
    'app/http/controllers/core/admin',
    'app/http/controllers/file/admin',
    'app/http/controllers/log/admin',
    'app/http/controllers/maintenance/admin',

    // ─── CMS module (page/template/builder) — main-only ───────────────────
    // The whole CMS domain is pruned: the module, its controllers (admin,
    // front AND api), transformers, events, listeners, mails, migrations,
    // seeders, i18n namespaces, the preview-token helper and the contact
    // email template — mirroring the `inertia` flavor's CMS delete map.
    'app/cms',
    'app/http/controllers/page',
    'app/http/controllers/template',
    'app/http/rest/pages.ts',
    'app/http/rest/templates.ts',
    'app/data/transformers/page',
    'app/data/transformers/template',
    'app/events/page',
    'app/listeners/page',
    'app/mails/page',
    'app/helpers/i18n_payloads/pages_create.ts',
    'app/helpers/i18n_payloads/pages_index.ts',
    'app/helpers/i18n_payloads/pages_show.ts',
    'app/helpers/i18n_payloads/page_editor.ts',
    'app/helpers/i18n_payloads/page_revisions.ts',
    'app/helpers/i18n_payloads/templates_edit.ts',
    'app/helpers/i18n_payloads/templates_index.ts',
    'app/helpers/core/preview_token.ts',
    'commands/cms_normalize_migration_names.ts',
    'database/migrations/cms',
    'database/seeders/page_seeder.ts',
    'database/seeders/template_seeder.ts',
    'resources/lang/en/page.json',
    'resources/lang/fr/page.json',
    'resources/lang/en/template.json',
    'resources/lang/fr/template.json',
    'resources/lang/en/builder.json',
    'resources/lang/fr/builder.json',
    'resources/views/emails/contact_form_email.edge',

    // ─── Transmit (real-time builder collaboration) — CMS-only ────────────
    'start/transmit.ts',
    'config/transmit.ts',
    'config/cms.ts',

    // ─── Route modules — unreferenced after the start/routes.ts rewrite ───
    'start/routes/front.routes.ts',
    'start/routes/core_public.routes.ts',
    'start/routes/cms_admin.routes.ts',
    'start/routes/cms_public.routes.ts',
    'start/routes/cms_rest_api.routes.ts',
    'start/routes/settings.routes.ts',
    'start/routes/admin.routes.ts',
    'start/routes/auth.routes.ts',

    // ─── Front test suites (browser E2E, Inertia-page functional, SEO, ────
    // ─── and the full-router structure snapshots of the pruned routes) ─────
    'tests/browser',
    'tests/functional/dashboard',
    'tests/functional/maintenance',
    'tests/functional/core/seo_endpoints.spec.ts',
    'tests/functional/cms/admin_dashboard_cms.spec.ts',
    'tests/integration/routes_structure.spec.ts',
    'tests/integration/routes_structure_cms.spec.ts',
    'tests/unit/rest/page_resource.spec.ts',

    // ─── CMS test suites ──────────────────────────────────────────────────
    'tests/functional/cms',
    'tests/unit/actions/page',
    'tests/unit/actions/template',
    'tests/unit/actions/cms',
    'tests/unit/models/page',
    'tests/unit/models/page.spec.ts',
    'tests/unit/models/page_translation.spec.ts',
    'tests/unit/models/template',
    'tests/unit/services/page',
    'tests/unit/services/template',
    'tests/unit/services/cms',
    'tests/unit/validators/page_validator.spec.ts',
    'tests/unit/validators/template_validator.spec.ts',
    'tests/unit/validators/builder_validator.spec.ts',
    'tests/unit/validators/contact_validator.spec.ts',
    'tests/unit/exceptions_cms.spec.ts',
    'tests/unit/mails/notifications_cms.spec.ts',
    'tests/unit/helpers/core/preview_token.spec.ts',
    'tests/unit/helpers/i18n_payloads_cms.spec.ts',
    'tests/integration/repositories/page_repository.spec.ts',
    'tests/integration/repositories/page_translation_repository.spec.ts',
    'tests/integration/repositories/page_revision_repository.spec.ts',
    'tests/integration/repositories/template_repository.spec.ts',
    'tests/integration/services/page/page_sitemap_collector.spec.ts',

    // ─── Playwright-only test helpers — the REST suites keep the two ──────
    // ─── DB-seeding helpers (create_admin_user, create_verified_user). ─────
    'tests/helpers/browser/login.ts',
    'tests/helpers/browser/visit_page.ts',
    'tests/helpers/browser/fill_field.ts',
    'tests/helpers/browser/field_is_filled.ts',
    'tests/helpers/browser/seed_dashboard.ts',
    'tests/helpers/browser/wait_for_builder_ready.ts',
    'tests/helpers/browser/wait_for_inertia_response.ts',

    // ─── Prune pipeline (main-only infrastructure) ────────────────────────
    'tooling/prune',
    'tests/unit/prune',

    // ─── Generated indexes — regenerated headless against the pruned ──────
    // ─── tree so zero view-layer references survive (init hooks + ready ────
    // ─── hook + Tuyau routesScanned regenerate the whole .adonisjs dir). ────
    '.adonisjs',
  ],

  rewrites: [
    // ─── config/features.ts — drop the session UI surfaces ───────────────
    {
      path: 'config/features.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Feature flags',
        '|--------------------------------------------------------------------------',
        '|',
        '| Runtime toggles to enable or disable route modules.',
        '| All features are enabled by default — change a boolean to',
        '| deactivate a module at runtime without touching routing code.',
        '|',
        '| The `api` flavor prunes the entire Inertia/Vite view layer AND the',
        '| CMS module (the CMS lives on `main` only): the session-rendered',
        '| auth, settings and admin surfaces are `false`, `cms` is `false`, and',
        '| only the non-CMS token-guarded REST layer (`adminApi`) stays on.',
        '*/',
        '',
        'export default {',
        '  auth: false,',
        '  settings: false,',
        '  admin: false,',
        '  adminApi: true,',
        '  cms: false,',
        '  maintenance: true,',
        '} as const',
        '',
      ].join('\n'),
    },

    // ─── start/routes.ts — REST-only route module index ──────────────────
    {
      path: 'start/routes.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Routes file',
        '|--------------------------------------------------------------------------',
        '|',
        '| Route module index — each domain registers its own routes.',
        '| Feature flags in config/features.ts gate each module at runtime.',
        '|',
        '| The `api` flavor is headless: no Inertia routes, no public site. The',
        '| whole backend is the versioned REST surface — the identity/token',
        '| API (`/api/v1/auth`, ...) and the admin REST API (`/api/v1/admin`, ...)',
        '| — plus the OAuth redirect/callback pair (social login issues an API',
        '| token and redirects to `AUTH_API_CLIENT_URL`) and the health endpoints',
        '| outside the maintenance wrapper.',
        '*/',
        '',
        "import features from '#config/features'",
        "import router from '@adonisjs/core/services/router'",
        "import { enabledAuthGuards } from '#config/auth'",
        "import { controllers } from '#generated/controllers'",
        "import { registerAdminRestApiRoutes } from '#start/routes/admin_rest_api.routes'",
        "import { registerApiRoutes } from '#start/routes/api.routes'",
        "import { registerHealthRoutes } from '#start/routes/health.routes'",
        "import { middleware } from '#start/kernel'",
        '',
        '// Health routes are outside maintenance middleware (liveness/readiness probes)',
        'registerHealthRoutes()',
        '',
        '// Wrap all feature routes with maintenance middleware',
        '// Health routes are registered separately above (outside this wrapper)',
        '',
        'router',
        '  .group(() => {',
        '    // OAuth redirect + callback — the browser round-trip completes here and',
        '    // the callback issues an API token (spec #6 social API mode).',
        '    router',
        '      .group(() => {',
        "        router.get('/:provider', [controllers.auth.api.SocialApi, 'redirect']).as('redirect')",
        '        router',
        "          .get('/:provider/callback', [controllers.auth.api.SocialApi, 'callback'])",
        "          .as('callback')",
        '      })',
        "      .prefix('oauth')",
        "      .as('auth.social')",
        '',
        '    // Admin REST surface (token-guarded).',
        '    if (features.adminApi) registerAdminRestApiRoutes()',
        '',
        '    // Token-guarded identity/register REST API — only when the `api` guard',
        '    // is enabled and the `adminApi` surface is on.',
        '    if (features.adminApi && enabledAuthGuards.api) registerApiRoutes()',
        '  })',
        '  .use(features.maintenance ? middleware.maintenance() : [])',
        '',
      ].join('\n'),
    },

    // ─── config/database.ts — drop the CMS migration folder ─────────────────
    {
      path: 'config/database.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/lucid'",
        '',
        'const dbConfig = defineConfig({',
        '  /**',
        '   * Default connection used for all queries.',
        '   */',
        "  connection: 'pg',",
        '',
        '  connections: {',
        '    /**',
        '     * SQLite connection (default).',
        '     */',
        '    sqlite: {',
        "      client: 'better-sqlite3',",
        '',
        '      connection: {',
        '        /**',
        '         * Database file location.',
        '         */',
        "        filename: app.tmpPath('db.sqlite3'),",
        '      },',
        '',
        '      /**',
        '       * Required by Knex for SQLite defaults.',
        '       */',
        '      useNullAsDefault: true,',
        '',
        '      migrations: {',
        '        /**',
        '         * Sort migration files naturally by filename.',
        '         */',
        '        naturalSort: true,',
        '',
        '        /**',
        '         * Paths containing migration files. The `api` flavor prunes the',
        '         * CMS module, so `database/migrations/cms` is absent.',
        '         */',
        "        paths: ['database/migrations'],",
        '      },',
        '    },',
        '',
        '    /**',
        '     * PostgreSQL connection.',
        '     * Install package to switch: npm install pg',
        '     */',
        '    pg: {',
        "      client: 'pg',",
        '      connection: {',
        '        host: process.env.PG_HOST,',
        '        port: Number(process.env.PG_PORT || 5432),',
        '        user: process.env.PG_USER,',
        '        password: process.env.PG_PASSWORD,',
        '        database: process.env.PG_DB_NAME,',
        '      },',
        '      migrations: {',
        '        naturalSort: true,',
        "        paths: ['database/migrations'],",
        '      },',
        '      debug: app.inDev,',
        '    },',
        '',
        '    /**',
        '     * MySQL / MariaDB connection.',
        '     * Install package to switch: npm install mysql2',
        '     */',
        '    // mysql: {',
        '    //   client: "mysql2",',
        '    //   connection: {',
        '    //     host: process.env.MYSQL_HOST,',
        '    //     port: Number(process.env.MYSQL_PORT || 3306),',
        '    //     user: process.env.MYSQL_USER,',
        '    //     password: process.env.MYSQL_PASSWORD,',
        '    //     database: process.env.MYSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * Microsoft SQL Server connection.',
        '     * Install package to switch: npm install tedious',
        '     */',
        '    // mssql: {',
        '    //   client: "mssql",',
        '    //   connection: {',
        '    //     server: process.env.MSSQL_SERVER,',
        '    //     port: Number(process.env.MSSQL_PORT || 1433),',
        '    //     user: process.env.MSSQL_USER,',
        '    //     password: process.env.MSSQL_PASSWORD,',
        '    //     database: process.env.MSSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * libSQL (Turso) connection.',
        '     * Install package to switch: npm install @libsql/client',
        '     */',
        '    // libsql: {',
        '    //   client: "libsql",',
        '    //   connection: {',
        '    //     url: process.env.LIBSQL_URL,',
        '    //     authToken: process.env.LIBSQL_AUTH_TOKEN,',
        '    //   },',
        '    //   useNullAsDefault: true,',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '  },',
        '})',
        '',
        'export default dbConfig',
        '',
      ].join('\n'),
    },

    // ─── config/shield.ts — drop the CMS iframe frame-src hosts ─────────────
    {
      path: 'config/shield.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/shield'",
        '',
        '/**',
        ' * CSP configuration for the `api` flavor.',
        ' *',
        ' * The CMS `iframe` block (and its `frame-src` host allowlist) is pruned in',
        ' * this flavor, so the CMS-specific imports are gone and the `frame-src`',
        ' * directive falls back to the default origin-only policy.',
        ' */',
        'const shieldConfig = defineConfig({',
        '  /**',
        '   * Configure CSP policies for your app. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csp: {',
        '    /**',
        '     * Enable the Content-Security-Policy header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Report violations without blocking resources in dev/test.',
        '     * Enforce in production.',
        '     */',
        '    reportOnly: app.inDev || app.inTest,',
        '',
        '    /**',
        '     * Per-resource CSP directives.',
        '     */',
        '    directives: {',
        '      // Default: only same-origin',
        '      defaultSrc: ["\'self\'"],',
        '',
        '      // Scripts: self + Vite HMR in dev/test',
        '      scriptSrc: [',
        '        "\'self\'",',
        '        ...(app.inDev || app.inTest ? ["\'unsafe-eval\'", "\'unsafe-inline\'"] : []), // Vite HMR needs these in dev/test',
        '      ],',
        '',
        '      // Styles: self + Tailwind JIT inline styles',
        '      styleSrc: ["\'self\'", "\'unsafe-inline\'"],',
        '',
        '      // Images: self + data: URIs + HTTPS',
        "      imgSrc: [\"'self'\", 'data:', 'https:'],",
        '',
        '      // Fonts: self + data: (for inline fonts)',
        "      fontSrc: [\"'self'\", 'data:'],",
        '',
        '      // Connect: self + SSE + Vite HMR websocket + Sentry',
        '      connectSrc: [',
        '        "\'self\'",',
        "        ...(app.inDev || app.inTest ? ['ws:', 'wss:'] : []), // Vite HMR websocket",
        "        'https://*.sentry.io', // Sentry error reporting",
        '      ],',
        '',
        '      // Frames: default to same-origin only — the CMS iframe block is pruned.',
        '      frameSrc: ["\'self\'"],',
        '',
        '      // Frames: deny (xFrame also set to SAMEORIGIN)',
        '      frameAncestors: ["\'none\'"],',
        '',
        '      // Forms: self only',
        '      formAction: ["\'self\'"],',
        '',
        '      // Base URI: self',
        '      baseUri: ["\'self\'"],',
        '',
        '      // Object/embed: none',
        '      objectSrc: ["\'none\'"],',
        '',
        '      // Media: self + external direct video files (video block)',
        "      mediaSrc: [\"'self'\", 'https:'],",
        '',
        '      // Workers: self',
        '      workerSrc: ["\'self\'"],',
        '',
        '      // Manifest: self',
        '      manifestSrc: ["\'self\'"],',
        '    },',
        '  },',
        '',
        '  /**',
        '   * Configure CSRF protection options. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csrf: {',
        '    /**',
        '     * Enable CSRF token verification for state-changing requests.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Routes to exclude from CSRF checks. Useful for external webhooks or',
        '     * API endpoints. Patterns match `ctx.route.pattern` exactly (no glob),',
        '     * hence the function form.',
        '     *',
        '     * `/api/v1/*` is the token-guarded REST API: Bearer-token requests carry',
        '     * no cookies, so they are not exposed to CSRF. Session-authenticated API',
        '     * routes (`/api/admin/*`, `/api/settings/*`) keep full CSRF protection.',
        '     */',
        '    exceptRoutes: (ctx) =>',
        "      ctx.route !== undefined && ctx.route.pattern.replace(/^\\//, '').startsWith('api/v1/'),",
        '',
        '    /**',
        '     * Expose an encrypted XSRF-TOKEN cookie for frontend HTTP clients.',
        '     */',
        '    enableXsrfCookie: true,',
        '',
        '    /**',
        '     * HTTP methods protected by CSRF validation.',
        '     */',
        "    methods: ['POST', 'PUT', 'PATCH', 'DELETE'],",
        '  },',
        '',
        '  /**',
        '   * Control how your website should be embedded inside',
        '   * iframes.',
        '   */',
        '  xFrame: {',
        '    /**',
        '     * Enable the X-Frame-Options header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Block all framing attempts. Default value is DENY.',
        '     */',
        "    action: 'SAMEORIGIN',",
        '  },',
        '',
        '  /**',
        '   * Force browser to always use HTTPS.',
        '   */',
        '  hsts: {',
        '    /**',
        '     * Enable the Strict-Transport-Security header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * HSTS policy duration remembered by browsers.',
        '     */',
        "    maxAge: '180 days',",
        '  },',
        '',
        '  /**',
        '   * Disable browsers from sniffing content types and rely only',
        '   * on the response content-type header.',
        '   */',
        '  contentTypeSniffing: {',
        '    /**',
        '     * Enable X-Content-Type-Options: nosniff.',
        '     */',
        '    enabled: true,',
        '  },',
        '})',
        '',
        'export default shieldConfig',
        '',
      ].join('\n'),
    },

    // ─── start/events.ts — drop the CMS contact-form listener ───────────────
    {
      path: 'start/events.ts',
      content: [
        "import emitter from '@adonisjs/core/services/emitter'",
        "import { events } from '#generated/events'",
        "import { listeners } from '#generated/listeners'",
        '',
        "emitter.on(events.auth.UserRegistered, [listeners.auth.SendVerificationEmail, 'handle'])",
        '',
        "emitter.on(events.auth.ForgotPassword, [listeners.auth.SendForgotPasswordEmail, 'handle'])",
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailNotificationEmail,',
        "  'handle',",
        '])',
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailConfirmationEmail,',
        "  'handle',",
        '])',
        '',
        "emitter.on(events.admin.InviteUser, [listeners.admin.SendInvitationEmail, 'handle'])",
        '',
      ].join('\n'),
    },

    // ─── start/nav.ts — drop the page + template nav entries ────────────────
    {
      path: 'start/nav.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Admin navigation composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the admin navigation entries of every domain existing in this',
        '| flavor of the application, in sidebar order. This file is part of the',
        "| composition set that flavor manifests may rewrite: remove a domain's",
        '| registration and its entries disappear from the admin sidebar.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { NavRegistry } from '#services/core/nav_registry'",
        "import { coreNavEntries } from '#services/core/core_nav'",
        "import { authNavEntries } from '#services/auth/auth_nav'",
        "import { fileNavEntries } from '#services/file/file_nav'",
        "import { maintenanceNavEntries } from '#services/maintenance/maintenance_nav'",
        "import { loggingNavEntries } from '#services/logging/logging_nav'",
        '',
        'app.container.singleton(NavRegistry, () => new NavRegistry())',
        '',
        'const registry = await app.container.make(NavRegistry)',
        '',
        "registry.register('core', coreNavEntries)",
        "registry.register('file', fileNavEntries)",
        "registry.register('auth', authNavEntries)",
        "registry.register('maintenance', maintenanceNavEntries)",
        "registry.register('logging', loggingNavEntries)",
        '',
      ].join('\n'),
    },

    // ─── start/dashboard.ts — drop the page + template collectors ───────────
    {
      path: 'start/dashboard.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Dashboard composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the dashboard section collectors of every domain existing in',
        '| this flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its section disappears from the admin dashboard.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { DashboardRegistry } from '#services/core/dashboard_registry'",
        "import { AuthDashboardCollector } from '#services/auth/auth_dashboard_collector'",
        "import { FileDashboardCollector } from '#services/file/file_dashboard_collector'",
        '',
        'app.container.singleton(DashboardRegistry, () => new DashboardRegistry())',
        '',
        'const registry = await app.container.make(DashboardRegistry)',
        '',
        "registry.register('auth', () => app.container.make(AuthDashboardCollector))",
        "registry.register('file', () => app.container.make(FileDashboardCollector))",
        '',
      ].join('\n'),
    },

    // ─── start/sitemap.ts — drop the page contributor (routes only) ─────────
    {
      path: 'start/sitemap.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Sitemap composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the sitemap contributors of every domain existing in this',
        '| flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its URLs disappear from `sitemap.xml`.',
        '|',
        '| The route collector is always present (hand-written `front.*` routes',
        '| exist in every flavor with a public front). The page collector is',
        '| CMS-specific and is removed by the `inertia` flavor manifest.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { SitemapRegistry } from '#services/core/sitemap_registry'",
        "import { RouteSitemapCollector } from '#services/core/route_sitemap_collector'",
        '',
        'app.container.singleton(SitemapRegistry, () => new SitemapRegistry())',
        '',
        'const registry = await app.container.make(SitemapRegistry)',
        '',
        "registry.register('routes', () => app.container.make(RouteSitemapCollector))",
        '',
      ].join('\n'),
    },

    // ─── start/container.ts — drop the builder session binding ──────────────
    {
      path: 'start/container.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { BackupEngine } from '#services/backup/backup_engine'",
        "import { CacheService } from '#services/cache/cache_service'",
        "import { RedisCacheDriver } from '#services/cache/drivers/redis_cache_driver'",
        "import { LogService } from '#services/logging/log_service'",
        "import { MaintenanceService } from '#services/maintenance/maintenance_service'",
        '',
        '/**',
        ' * IoC container bindings.',
        ' *',
        ' * Singleton services are instantiated exactly once per process and reused',
        ' * across every request — which is what makes in-flight state (locks,',
        ' * sessions) work correctly without serialising to a database on every call.',
        ' * Factory bindings are re-created on each resolution with runtime arguments',
        ' * supplied via {@link app.container.make}.',
        ' *',
        " * Add this file to `adonisrc.ts` preloads if it isn't already:",
        ' *',
        ' * @example',
        ' * // adonisrc.ts',
        ' * preloads: [',
        " *   () => import('#start/container'),",
        ' * ]',
        ' */',
        '',
        '// ─── BackupEngine (factory) ────────────────────────────────────────────',
        '',
        '/**',
        ' * Factory binding for {@link BackupEngine} so that callers can resolve it',
        ' * through the container instead of using `new`. Runtime arguments',
        ' * (`strategyType`, `tempDir`) are supplied at resolution time which keeps',
        ' * the strategy dynamic while still being mockable in tests via',
        ' * {@link app.container.swap}.',
        ' *',
        ' * @example',
        " * const engine = await app.container.make(BackupEngine, ['full', 'storage/temp/backups'])",
        ' */',
        'app.container.bind(BackupEngine, async (resolver, runtimeValues) => {',
        '  const [strategyType, tempDir] = runtimeValues ?? []',
        '  const logService = await resolver.make(LogService)',
        '  return new BackupEngine(strategyType, tempDir, logService)',
        '})',
        '',
        '// ─── CacheService (singleton) ──────────────────────────────────────────',
        '',
        '/**',
        ' * The root `CacheService` backed by Redis.',
        ' * Inject or resolve via the container anywhere in the app:',
        ' *',
        ' * @example',
        ' * // In a service or controller',
        ' * const cache = await app.container.make(CacheService)',
        ' */',
        'app.container.singleton(CacheService, () => {',
        '  const driver = new RedisCacheDriver()',
        '  return new CacheService(driver)',
        '})',
        '',
        '// ─── MaintenanceService (singleton) ────────────────────────────────────',
        '',
        '/**',
        ' * Maintenance service singleton.',
        ' * Handles Redis + memory fallback for maintenance mode configuration.',
        ' * Initializes memory fallback on first resolution.',
        ' */',
        'app.container.singleton(MaintenanceService, async () => {',
        '  const service = MaintenanceService.getInstance()',
        '  await service.initializeMemoryFallback()',
        '  return service',
        '})',
        '',
      ].join('\n'),
    },

    // ─── config/cors.ts — explicit env-driven allowlist (first-class) ────
    {
      path: 'config/cors.ts',
      content: [
        "import { defineConfig } from '@adonisjs/cors'",
        "import env from '#start/env'",
        '',
        '/**',
        ' * Configuration options to tweak the CORS policy. The following',
        ' * options are documented on the official documentation website.',
        ' *',
        ' * https://docs.adonisjs.com/guides/security/cors',
        ' */',
        'const corsConfig = defineConfig({',
        '  /**',
        '   * Enable or disable CORS handling globally.',
        '   */',
        '  enabled: true,',
        '',
        '  /**',
        '   * Explicit allowlist of cross-origin front origins, taken from the',
        '   * `CORS_ALLOWED_ORIGINS` environment variable (comma-separated). The',
        '   * `api` flavor is consumed by external fronts by definition, so CORS is',
        '   * a config step — never a code change.',
        '   */',
        '  origin: env',
        "    .get('CORS_ALLOWED_ORIGINS', '')",
        "    .split(',')",
        '    .map((origin) => origin.trim())',
        '    .filter((origin) => origin.length > 0),',
        '',
        '  /**',
        '   * HTTP methods accepted for cross-origin requests.',
        '   */',
        "  methods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE'],",
        '',
        '  /**',
        '   * Reflect request headers by default. Use a string array to restrict',
        '   * allowed headers.',
        '   */',
        '  headers: true,',
        '',
        '  /**',
        '   * Response headers exposed to the browser.',
        '   */',
        '  exposeHeaders: [],',
        '',
        '  /**',
        '   * Allow cookies/authorization headers on cross-origin requests.',
        '   */',
        '  credentials: true,',
        '',
        '  /**',
        '   * Cache CORS preflight response for N seconds.',
        '   */',
        '  maxAge: 90,',
        '})',
        '',
        'export default corsConfig',
        '',
      ].join('\n'),
    },

    // ─── start/asset_middleware.ts — no view-layer asset middleware ──────
    {
      path: 'start/asset_middleware.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| View-layer asset middleware composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| The `api` flavor drops the entire Inertia/Vite stack, so no asset',
        '| middleware is registered. `start/kernel.ts` keeps its single',
        '| unconditional reference and this array is simply empty.',
        '|',
        '*/',
        '',
        'export const assetMiddleware = []',
        '',
      ].join('\n'),
    },

    // ─── start/env.ts — add the CORS allowlist variable ──────────────────
    {
      path: 'start/env.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Environment variables service',
        '|--------------------------------------------------------------------------',
        '|',
        '| The `Env.create` method creates an instance of the Env service. The',
        '| service validates the environment variables and also cast values',
        '| to JavaScript data types.',
        '|',
        '*/',
        '',
        "import { Env } from '@adonisjs/core/env'",
        '',
        "export default await Env.create(new URL('../', import.meta.url), {",
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring node',
        '  |----------------------------------------------------------',
        '  */',
        "  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),",
        '  PORT: Env.schema.number(),',
        "  HOST: Env.schema.string({ format: 'host' }),",
        '  LOG_LEVEL: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring app',
        '  |----------------------------------------------------------',
        '  */',
        '  APP_KEY: Env.schema.secret(),',
        "  APP_URL: Env.schema.string({ format: 'url', tld: false }),",
        '  APP_NAME: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring CORS',
        '  |----------------------------------------------------------',
        '  |',
        "  | Comma-separated allowlist of external front origins the `api` flavor's",
        '  | REST API accepts cross-origin. Empty by default (no cross-origin',
        '  | browser access until configured).',
        '  |',
        '  */',
        '  CORS_ALLOWED_ORIGINS: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring session',
        '  |----------------------------------------------------------',
        '  */',
        "  SESSION_DRIVER: Env.schema.enum(['cookie', 'memory', 'database', 'redis'] as const),",
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the auth guards',
        '  |----------------------------------------------------------',
        '  |',
        '  | Which authentication mechanisms are active. full/inertia keep the',
        '  | session guard and may opt into the token guard (REST API); the api',
        '  | flavor disables the session guard entirely (`AUTH_GUARD_WEB=false`)',
        '  | and authenticates exclusively through API tokens.',
        '  |',
        '  */',
        '  AUTH_GUARD_WEB: Env.schema.boolean.optional(),',
        '  AUTH_GUARD_API: Env.schema.boolean.optional(),',
        '  AUTH_API_TOKEN_EXPIRY: Env.schema.string.optional(),',
        '  AUTH_API_CLIENT_URL: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring database connection',
        '  |----------------------------------------------------------',
        '  */',
        "  PG_HOST: Env.schema.string({ format: 'host' }),",
        '  PG_PORT: Env.schema.number(),',
        '  PG_USER: Env.schema.string(),',
        '  PG_PASSWORD: Env.schema.secret(),',
        '  PG_DB_NAME: Env.schema.string(),',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Variables for configuring @adonisjs/redis package',
        '  |--------------------------------------------------------------------------',
        '  */',
        "  REDIS_HOST: Env.schema.string({ format: 'host' }),",
        '  REDIS_PORT: Env.schema.number(),',
        '  REDIS_PASSWORD: Env.schema.string.optional(),',
        '  REDIS_SOCKET: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the mail package',
        '  |----------------------------------------------------------',
        '  */',
        "  MAIL_MAILER: Env.schema.enum(['smtp'] as const),",
        '  MAIL_FROM_NAME: Env.schema.string(),',
        '  MAIL_FROM_ADDRESS: Env.schema.string(),',
        '  SMTP_HOST: Env.schema.string(),',
        '  SMTP_PORT: Env.schema.number(),',
        '  SMTP_USERNAME: Env.schema.string(),',
        '  SMTP_PASSWORD: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the Sentry SDK',
        '  |----------------------------------------------------------',
        '  */',
        '  SENTRY_DSN: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the ally (OAuth) package',
        '  |----------------------------------------------------------',
        '  */',
        '  FACEBOOK_CLIENT_ID: Env.schema.string.optional(),',
        '  FACEBOOK_CLIENT_SECRET: Env.schema.string.optional(),',
        '  GITHUB_CLIENT_ID: Env.schema.string.optional(),',
        '  GITHUB_CLIENT_SECRET: Env.schema.string.optional(),',
        '  GOOGLE_CLIENT_ID: Env.schema.string.optional(),',
        '  GOOGLE_CLIENT_SECRET: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration',
        '  |----------------------------------------------------------',
        '  */',
        "  BACKUP_STORAGE_DISK: Env.schema.enum.optional(['fs', 's3', 'r2'] as const),",
        '  BACKUP_TIME: Env.schema.string.optional(),',
        '  BACKUP_ENCRYPTION_ENABLED: Env.schema.boolean.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Retention',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_RETENTION_DAILY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_WEEKLY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_MONTHLY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_YEARLY: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Health Check',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_MAX_AGE_HOURS: Env.schema.number.optional(),',
        '  BACKUP_MAX_SIZE_MB: Env.schema.number.optional(),',
        '  BACKUP_MIN_FREE_SPACE_GB: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Notifications',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_NOTIFICATION_EMAIL: Env.schema.string.optional(),',
        '  BACKUP_NOTIFY_SUCCESS: Env.schema.boolean.optional(),',
        '  BACKUP_NOTIFY_FAILURE: Env.schema.boolean.optional(),',
        '  BACKUP_NOTIFY_HEALTH_CHECK: Env.schema.boolean.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Differential',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_EXCLUDED_TABLES: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the drive package',
        '  |----------------------------------------------------------',
        '  */',
        "  DRIVE_DISK: Env.schema.enum(['fs', 's3', 'r2'] as const),",
        '  AWS_ACCESS_KEY_ID: Env.schema.string.optional(),',
        '  AWS_SECRET_ACCESS_KEY: Env.schema.string.optional(),',
        '  AWS_REGION: Env.schema.string.optional(),',
        '  S3_BUCKET: Env.schema.string.optional(),',
        '  R2_KEY: Env.schema.string.optional(),',
        '  R2_SECRET: Env.schema.string.optional(),',
        '  R2_BUCKET: Env.schema.string.optional(),',
        '  R2_ENDPOINT: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring file upload',
        '  |----------------------------------------------------------',
        '  */',
        '  MAX_UPLOAD_SIZE: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the limiter package',
        '  |----------------------------------------------------------',
        '  */',
        "  LIMITER_STORE: Env.schema.enum(['redis', 'memory'] as const),",
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for sitemap.xml generation.',
        '  | Comma-separated lists; both have safe defaults in config/sitemap.ts.',
        '  |----------------------------------------------------------',
        '  */',
        '  SITEMAP_ADDITIONS: Env.schema.string.optional(),',
        '  SITEMAP_EXCLUSIONS: Env.schema.string.optional(),',
        '})',
        '',
      ].join('\n'),
    },

    // ─── .env.example — API-token-only template with CORS first-class ────
    {
      path: '.env.example',
      content: [
        '# Node',
        'TZ=UTC',
        'PORT=3333',
        'HOST=localhost',
        'NODE_ENV=development',
        '',
        '# App',
        'LOG_LEVEL=info',
        'APP_KEY=',
        'APP_URL=http://localhost:3333',
        'APP_NAME=AdonisJS Foundry',
        '',
        '# Session',
        'SESSION_DRIVER=redis',
        '',
        '# Auth guards — this flavor authenticates exclusively through API tokens.',
        '# AUTH_GUARD_WEB=false disables the session guard; the whole backend is driven',
        '# through /api/v1/* with Bearer tokens.',
        'AUTH_GUARD_WEB=false',
        'AUTH_GUARD_API=true',
        '# Default lifetime of issued API tokens (e.g. "30 days", "7d", "24h").',
        'AUTH_API_TOKEN_EXPIRY=30 days',
        '# Client-side callback URL for OAuth API mode (spec #6): after a provider',
        '# callback the backend issues an API token and redirects to this URL with',
        '# `?token=...&expires_at=...`. Leave empty to disable social login.',
        'AUTH_API_CLIENT_URL=',
        '',
        '# CORS — comma-separated allowlist of external front origins (your Next.js,',
        '# Nuxt, mobile bundle origin, ...). Empty = no cross-origin browser access.',
        '# This is the first config step when connecting a cross-origin front.',
        'CORS_ALLOWED_ORIGINS=',
        '',
        '# Database',
        'PG_HOST=127.0.0.1',
        'PG_PORT=5432',
        'PG_USER=user',
        'PG_PASSWORD=password',
        'PG_DB_NAME=app',
        '',
        '# Redis',
        'REDIS_HOST=127.0.0.1',
        'REDIS_PORT=6379',
        'REDIS_PASSWORD=',
        'REDIS_SOCKET=',
        '',
        '# Mail',
        'MAIL_MAILER=smtp',
        'MAIL_FROM_NAME=${APP_NAME}',
        'MAIL_FROM_ADDRESS=contact@example.com',
        '',
        '# SMTP',
        'SMTP_HOST=localhost',
        'SMTP_PORT=1025',
        'SMTP_USERNAME=username',
        'SMTP_PASSWORD=password',
        '',
        '# Sentry',
        'SENTRY_DSN=<your_dsn_url>',
        '',
        '# Oauth',
        'FACEBOOK_CLIENT_ID=',
        'FACEBOOK_CLIENT_SECRET=',
        'GITHUB_CLIENT_ID=',
        'GITHUB_CLIENT_SECRET=',
        'GOOGLE_CLIENT_ID=',
        'GOOGLE_CLIENT_SECRET=',
        'DRIVE_DISK=fs',
        'AWS_ACCESS_KEY_ID=',
        'AWS_SECRET_ACCESS_KEY=',
        'AWS_REGION=',
        'S3_BUCKET=',
        'R2_KEY=',
        'R2_SECRET=',
        'R2_BUCKET=',
        'R2_ENDPOINT=',
        'LIMITER_STORE=redis',
        '',
      ].join('\n'),
    },

    // ─── adonisrc.ts — drop the Inertia/Vite providers and asset hooks ───
    {
      path: 'adonisrc.ts',
      content: [
        "import { indexEntities } from '@adonisjs/core'",
        "import { defineConfig } from '@adonisjs/core/app'",
        "import { generateRegistry } from '@tuyau/core/hooks'",
        '',
        'export default defineConfig({',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Experimental flags',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | The following features will be enabled by default in the next major',
        '  | release of AdonisJS. You can opt into them today to avoid any breaking',
        '  | changes during upgrade.',
        '  |',
        '  */',
        '  experimental: {},',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Commands',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of ace commands to register from packages. The application',
        '  | commands will be scanned automatically from the "./commands" directory.',
        '  |',
        '  */',
        '  commands: [',
        "    () => import('@adonisjs/core/commands'),",
        "    () => import('@adonisjs/lucid/commands'),",
        "    () => import('@adonisjs/session/commands'),",
        "    () => import('@adonisjs/mail/commands'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Directories',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  */',
        '  directories: {',
        "    httpControllers: 'app/http/controllers',",
        "    transformers: 'app/data/transformers',",
        "    middleware: 'app/http/middleware',",
        "    services: 'app/domain/services',",
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Service providers',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of service providers to import and register when booting the',
        '  | application',
        '  |',
        '  | The `api` flavor is headless and CMS-less: the Inertia, Vite and',
        '  | Transmit providers are all gone.',
        '  |',
        '  */',
        '  providers: [',
        "    () => import('@adonisjs/core/providers/app_provider'),",
        "    () => import('@adonisjs/core/providers/hash_provider'),",
        '    {',
        "      file: () => import('@adonisjs/core/providers/repl_provider'),",
        "      environment: ['repl', 'test'],",
        '    },',
        "    () => import('@adonisjs/core/providers/vinejs_provider'),",
        "    () => import('@adonisjs/core/providers/edge_provider'),",
        "    () => import('@adonisjs/session/session_provider'),",
        "    () => import('@adonisjs/shield/shield_provider'),",
        "    () => import('@adonisjs/static/static_provider'),",
        "    () => import('@adonisjs/lucid/database_provider'),",
        "    () => import('@adonisjs/cors/cors_provider'),",
        "    () => import('@adonisjs/auth/auth_provider'),",
        "    () => import('#providers/api_provider'),",
        "    () => import('@adonisjs/redis/redis_provider'),",
        "    () => import('#providers/sentry_provider'),",
        "    () => import('@adonisjs/i18n/i18n_provider'),",
        "    () => import('@adonisjs/ally/ally_provider'),",
        "    () => import('@adonisjs/mail/mail_provider'),",
        "    () => import('@adonisjs/drive/drive_provider'),",
        "    () => import('@adonisjs/limiter/limiter_provider'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Preloads',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of modules to import before starting the application.',
        '  |',
        '  */',
        '  preloads: [',
        "    () => import('#start/routes'),",
        "    () => import('#start/kernel'),",
        "    () => import('#start/validator'),",
        "    () => import('#start/events'),",
        "    () => import('#start/container'),",
        "    () => import('#start/dashboard'),",
        "    () => import('#start/sitemap'),",
        "    () => import('#start/nav'),",
        "    () => import('#start/extensions'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Tests',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of test suites to organize tests by their type. Feel free to',
        '  | remove and add additional suites. The `browser` suite stays declared',
        '  | but is empty: no view layer exists to drive with Playwright.',
        '  |',
        '  */',
        '  tests: {',
        '    suites: [',
        '      {',
        "        files: ['tests/unit/**/*.spec.{ts,js}'],",
        "        name: 'unit',",
        '        timeout: 2000,',
        '      },',
        '      {',
        "        files: ['tests/integration/**/*.spec.{ts,js}'],",
        "        name: 'integration',",
        '        timeout: 5000,',
        '      },',
        '      {',
        "        files: ['tests/functional/**/*.spec.{ts,js}'],",
        "        name: 'functional',",
        '        timeout: 30000,',
        '      },',
        '      {',
        "        files: ['tests/browser/**/*.spec.{ts,js}'],",
        "        name: 'browser',",
        '        timeout: 300000,',
        '      },',
        '    ],',
        '    forceExit: false,',
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Metafiles',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | A collection of files you want to copy to the build folder when',
        '  | creating the production build.',
        '  |',
        '  */',
        '  metaFiles: [',
        '    {',
        "      pattern: 'resources/views/**/*.edge',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'public/**',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'resources/lang/**/*.{json,yaml,yml}',",
        '      reloadServer: false,',
        '    },',
        '  ],',
        '',
        '  hooks: {',
        '    init: [',
        '      indexEntities({',
        '        transformers: {',
        '          enabled: true,',
        '          withSharedProps: false,',
        "          source: 'app/data/transformers',",
        "          importAlias: '#transformers',",
        "          glob: ['**\\/*transformer.ts'],",
        '        },',
        '        controllers: {',
        '          enabled: true,',
        "          source: 'app/http/controllers',",
        "          importAlias: '#controllers',",
        "          glob: ['**\\/*_controller.ts'],",
        '        },',
        '      }),',
        '      generateRegistry(),',
        '    ],',
        '  },',
        '})',
        '',
      ].join('\n'),
    },

    // ─── package.json — drop the front build/dev/test scripts and deps ───
    {
      path: 'package.json',
      content: [
        '{',
        '  "name": "adonisjs-foundry",',
        '  "version": "1.4.0",',
        '  "private": true,',
        '  "type": "module",',
        '  "license": "UNLICENSED",',
        '  "engines": {',
        '    "node": ">=24.0.0"',
        '  },',
        '  "scripts": {',
        '    "start": "node bin/server.js",',
        '    "build": "node ace build",',
        '    "dev": "node ace serve --hmr",',
        '    "docker:up": "docker compose up -d",',
        '    "docker:stop": "docker compose stop -d",',
        '    "test": "node ace test",',
        '    "lint": "eslint . --fix",',
        '    "lint:ci": "eslint .",',
        '    "format": "prettier --write .",',
        '    "format:ci": "prettier --check .",',
        '    "typecheck": "tsc --noEmit",',
        '    "postinstall": "patch-package"',
        '  },',
        '  "imports": {',
        '    "#controllers/*": "./app/http/controllers/*.js",',
        '    "#exceptions/*": "./app/exceptions/*.js",',
        '    "#helpers/*": "./app/helpers/*.js",',
        '    "#models/*": "./app/models/*.js",',
        '    "#mails/*": "./app/mails/*.js",',
        '    "#listeners/*": "./app/listeners/*.js",',
        '    "#events/*": "./app/events/*.js",',
        '    "#generated/*": "./.adonisjs/server/*.js",',
        '    "#middleware/*": "./app/http/middleware/*.js",',
        '    "#rest/*": "./app/http/rest/*.js",',
        '    "#repositories/*": "./app/domain/repositories/*.js",',
        '    "#services/*": "./app/domain/services/*.js",',
        '    "#contracts/*": "./app/domain/contracts/*.js",',
        '    "#transformers/*": "./app/data/transformers/*.js",',
        '    "#types/*": "./app/types/*.js",',
        '    "#validators/*": "./app/validators/*.js",',
        '    "#providers/*": "./providers/*.js",',
        '    "#policies/*": "./app/policies/*.js",',
        '    "#abilities/*": "./app/abilities/*.js",',
        '    "#database/*": "./database/*.js",',
        '    "#factories/*": "./database/factories/*.js",',
        '    "#shared/*": "./app/shared/*.js",',
        '    "#tests/*": "./tests/*.js",',
        '    "#start/*": "./start/*.js",',
        '    "#config/*": "./config/*.js",',
        '    "#actions/*": "./app/domain/actions/*.js",',
        '    "#cms/*": "./app/cms/*.js"',
        '  },',
        '  "devDependencies": {',
        '    "@adonisjs/assembler": "^8.0.0",',
        '    "@adonisjs/eslint-config": "^3.0.0",',
        '    "@adonisjs/prettier-config": "^1.4.5",',
        '    "@adonisjs/tsconfig": "^2.0.0",',
        '    "@japa/api-client": "^3.2.1",',
        '    "@japa/assert": "^4.2.0",',
        '    "@japa/browser-client": "^2.3.0",',
        '    "@japa/plugin-adonisjs": "^5.1.0",',
        '    "@japa/runner": "^5.3.0",',
        '    "@playwright/test": "^1.62.1",',
        '    "@poppinss/ts-exec": "^1.4.4",',
        '    "@types/dompurify": "^3.2.0",',
        '    "@types/jsdom": "^28.0.1",',
        '    "@types/luxon": "^3.7.4",',
        '    "@types/node": "~26.2.0",',
        '    "@types/react": "^19.2.14",',
        '    "@types/react-dom": "^19.2.3",',
        '    "@types/sinon": "^22.0.0",',
        '    "@vitejs/plugin-react": "^5.1.4",',
        '    "eslint": "^10.8.1",',
        '    "hot-hook": "^1.0.0",',
        '    "pino-pretty": "^13.1.3",',
        '    "prettier": "^3.9.6",',
        '    "typescript": "~5.9.3",',
        '    "vite": "^7.3.1",',
        '    "vitest": "^4.1.10",',
        '    "youch": "^4.1.0"',
        '  },',
        '  "dependencies": {',
        '    "@adonisjs/ally": "^6.0.0",',
        '    "@adonisjs/auth": "^10.0.0",',
        '    "@adonisjs/core": "^7.0.0",',
        '    "@adonisjs/cors": "^3.0.0",',
        '    "@adonisjs/drive": "^4.0.0",',
        '    "@adonisjs/i18n": "^3.0.0",',
        '    "@adonisjs/inertia": "^4.2.0",',
        '    "@adonisjs/limiter": "^3.0.1",',
        '    "@adonisjs/lucid": "^22.0.0",',
        '    "@adonisjs/mail": "^10.0.0",',
        '    "@adonisjs/redis": "^10.0.0",',
        '    "@adonisjs/session": "^8.0.0",',
        '    "@adonisjs/shield": "^9.0.0",',
        '    "@adonisjs/static": "^2.0.0",',
        '    "@adonisjs/vite": "^5.1.0",',
        '    "@aws-sdk/client-s3": "^3.1102.0",',
        '    "@aws-sdk/s3-request-presigner": "^3.1102.0",',
        '    "@fontsource/cormorant-garamond": "^5.2.11",',
        '    "@fontsource/jost": "^5.3.0",',
        '    "@fontsource/playfair-display": "^5.3.0",',
        '    "@iconify/react": "^6.0.2",',
        '    "@inertiajs/react": "^2.3.22",',
        '    "@sentry/node": "^10.70.0",',
        '    "@tailwindcss/vite": "^4.2.1",',
        '    "@tuyau/core": "^1.0.0",',
        '    "@vinejs/vine": "^4.3.0",',
        '    "better-sqlite3": "^13.0.3",',
        '    "dompurify": "^3.4.13",',
        '    "edge.js": "^6.5.1",',
        '    "html-to-image": "^1.11.13",',
        '    "ipaddr.js": "^2.4.0",',
        '    "jsdom": "^29.0.1",',
        '    "luxon": "^3.7.2",',
        '    "patch-package": "^8.0.1",',
        '    "pg": "^8.22.0",',
        '    "react": "^19.2.4",',
        '    "react-dom": "^19.2.4",',
        '    "reflect-metadata": "^0.2.2",',
        '    "sharp": "^0.35.3",',
        '    "sinon": "^22.1.0",',
        '    "sonner": "^2.0.7",',
        '    "tailwindcss": "^4.3.3",',
        '    "uuid": "^14.0.1"',
        '  },',
        '  "hotHook": {',
        '    "boundaries": [',
        '      "./app/http/controllers/**/*.ts",',
        '      "./app/http/middleware/**/*.ts",',
        '      "./app/http/rest/**/*.ts"',
        '    ]',
        '  },',
        '  "prettier": "@adonisjs/prettier-config"',
        '}',
        '',
      ].join('\n'),
    },

    // ─── tsconfig.json — drop the Inertia project reference ──────────────
    {
      path: 'tsconfig.json',
      content: [
        '{',
        '  "extends": "@adonisjs/tsconfig/tsconfig.app.json",',
        '  "compilerOptions": {',
        '    "rootDir": "./",',
        '    "outDir": "./build"',
        '  }',
        '}',
        '',
      ].join('\n'),
    },

    // ─── README.md — flavor-specific surface documentation ───────────────
    {
      path: 'README.md',
      content: [
        '# AdonisJS Foundry — `api` flavor',
        '',
        'A production-ready AdonisJS v7 backend exposed as a pure versioned REST API — no Inertia, no React, no admin UI, no public site, no CMS. Every backend capability reaches your external front (Next.js, Nuxt, a mobile app) through `/api/v1/*` behind API token authentication.',
        '',
        '## What is included',
        '',
        '- **Versioned REST API** — identity/token auth (`/api/v1/auth`), profile and account (`/api/v1/profile`, `/api/v1/account`) and the admin surface (`/api/v1/admin`) for users, roles, permissions, files, folders, dashboard, logs and maintenance.',
        '- **API token authentication** — opaque Bearer tokens issued by `/api/v1/auth/login` (and `/register`). No cookies, no CSRF handling on the token-guarded surface.',
        '- **File management** — upload, folders, multi-disk storage (local, S3, R2) and public file serving through drive.',
        '- **Operational features** — Redis cache/locks, mail, i18n, rate limiting, audit logs, maintenance mode and a first-class CORS policy.',
        '',
        'No view layer and no CMS ship in this repository: the Inertia/React/Vite stack and the page/template/builder module live on `main` only. You bring the front, and it consumes the API.',
        '',
        '## Quick start',
        '',
        '```bash',
        'npm install',
        'cp .env.example .env',
        'node ace generate:key',
        'node ace migration:run',
        'npm run dev',
        '```',
        '',
        'The API is available at `http://localhost:3333/api/v1`.',
        '',
        '## Authentication flow',
        '',
        '1. `POST /api/v1/auth/login` with `email` + `password` returns the user payload and an API token.',
        '2. Send the token in the `Authorization: Bearer <token>` header on every authenticated request.',
        '3. `POST /api/v1/auth/logout` revokes the token; token lifetime is configured with `AUTH_API_TOKEN_EXPIRY` (default `30 days`).',
        '',
        'Registration, email verification, password reset and invitation acceptance are `POST /api/v1/auth/*` endpoints. The authenticated identity, profile and account endpoints live at `/api/v1/profile` and `/api/v1/account`.',
        '',
        '## Social login (OAuth API mode)',
        '',
        'OAuth providers (GitHub, Google, Facebook) work headless: open `/oauth/{provider}` in a browser or webview, and after the provider callback the backend issues an API token and redirects to `AUTH_API_CLIENT_URL` with `?token=...&expires_at=...`. Your mobile app reads the token from the redirect and uses it as a Bearer token from then on. With `AUTH_API_CLIENT_URL` unset, the `/oauth/*` callback returns a 500 config error rather than a session.',
        '',
        '## Admin surface (endpoint map)',
        '',
        'Under `/api/v1/admin`, each resource is a thin controller reusing the shared domain layer — administrators are just API claimers, and the surface is exactly the non-CMS one built on `main` (#6/#7):',
        '',
        '| Resource    | Endpoints                                                                                      |',
        '| ----------- | ---------------------------------------------------------------------------------------------- |',
        '| Users       | `GET/POST /users`, `GET/PUT/DELETE /users/:id`                                                 |',
        '| Roles       | `GET/POST /roles`, `GET/PUT/DELETE /roles/:id`                                                 |',
        '| Permissions | `GET /permissions`                                                                             |',
        '| Files       | `GET/POST /files`, `GET/DELETE /files/:id`, `PUT /files/:id/move`, `PUT/DELETE /files/:id/alt` |',
        '| Folders     | `GET/POST /folders`, `GET/PUT/DELETE /folders/:id`                                             |',
        '| Dashboard   | `GET /dashboard`                                                                               |',
        '| Logs        | `GET /logs`                                                                                    |',
        '| Maintenance | `GET/PUT /maintenance`, `PUT /maintenance/toggle`                                              |',
        '',
        'All of them require `Authorization: Bearer <token>` and enforce the usual permission middleware (`users.view`, `files.create`, ...).',
        '',
        '## CORS',
        '',
        'The REST API is consumed cross-origin by definition, so CORS is a config step, not a code change: set `CORS_ALLOWED_ORIGINS` in `.env` to a comma-separated list of your front origins',
        '',
        '```',
        'CORS_ALLOWED_ORIGINS=https://app.example.com,http://localhost:3000',
        '```',
        '',
        'Empty (the default) allows no cross-origin browser access.',
        '',
        '## Security headers',
        '',
        'The CSP and other security headers (shield) stay intact. External fronts connect through the API with Bearer tokens, and no CSRF cookie is involved on the token-guarded `/api/v1/*` surface.',
        '',
        '## Upgrade path to `full`',
        '',
        'Choosing this flavor is not a one-way door. See `docs/flavors/api/upgrade-to-full.md` for the documented manual path to recover the Inertia admin, the public site, the frontend tooling and the CMS.',
        '',
        '## Available scripts',
        '',
        '| Script              | Description                   |',
        '| ------------------- | ----------------------------- |',
        '| `npm run dev`       | Start the dev server with HMR |',
        '| `npm run build`     | Build for production          |',
        '| `npm start`         | Start the production server   |',
        '| `npm test`          | Run the backend test suite    |',
        '| `npm run lint`      | Run ESLint                    |',
        '| `npm run format`    | Format code with Prettier     |',
        '| `npm run typecheck` | Type-check the backend        |',
        '',
      ].join('\n'),
    },
  ],

  dependencies: {
    packages: [
      // Frontend runtime
      '@adonisjs/inertia',
      '@adonisjs/vite',
      '@inertiajs/react',
      'react',
      'react-dom',
      'sonner',
      'html-to-image',
      '@iconify/react',
      '@fontsource/cormorant-garamond',
      '@fontsource/jost',
      '@fontsource/playfair-display',
      'tailwindcss',
      '@tailwindcss/vite',
      // Frontend tooling
      '@vitejs/plugin-react',
      'vite',
      'vitest',
      '@types/react',
      '@types/react-dom',
      // CMS/real-time (main-only)
      '@adonisjs/transmit',
      '@adonisjs/transmit-client',
    ],
  },
}

export default apiManifest
