/**
 * `inertia` flavor manifest.
 *
 * Derives the hand-written-Inertia flavor from `main`: keeps the full admin
 * back-office (users, roles, permissions, files, logs, maintenance, settings,
 * dashboard) and the complete auth flow, prunes the `page` and `template`
 * domains and Transmit entirely, and ships a minimal hand-written front
 * (a blank home page and error pages, each served by its own `front.*`
 * controller).
 *
 * The delete inventory mirrors ADR-0001's CMS delete map: the whole `app/cms/`
 * module, every smeared CMS path outside it (controllers, transformers,
 * events, listeners, mails, i18n payload helpers, migrations, i18n, seeders,
 * tests), the Transmit integration, and the builder/template React subtrees.
 * The rewrites drop the CMS and Transmit registrations from the allowlisted
 * composition files and turn the `cms` feature flag off.
 *
 * Applied by {@link '../engine'} via
 * `node --import @poppinss/ts-exec tooling/prune/apply.ts inertia`.
 */
import type { FlavorManifest } from '#prune/types'

const inertiaManifest: FlavorManifest = {
  flavor: 'inertia',

  delete: [
    // ─── CMS module (page, template, builder) ───────────────────────────────
    'app/cms',

    // ─── CMS controllers (page + template) ──────────────────────────────────
    'app/http/controllers/page',
    'app/http/controllers/template',

    // ─── CMS transformers (page + template) ─────────────────────────────────
    'app/data/transformers/page',
    'app/data/transformers/template',

    // ─── CMS events and listeners ───────────────────────────────────────────
    'app/events/page',
    'app/listeners/page',

    // ─── CMS mail (contact form) ────────────────────────────────────────────
    'app/mails/page',

    // ─── CMS i18n payload helpers ───────────────────────────────────────────
    'app/helpers/i18n_payloads/pages_create.ts',
    'app/helpers/i18n_payloads/pages_index.ts',
    'app/helpers/i18n_payloads/pages_show.ts',
    'app/helpers/i18n_payloads/page_editor.ts',
    'app/helpers/i18n_payloads/page_revisions.ts',
    'app/helpers/i18n_payloads/templates_edit.ts',
    'app/helpers/i18n_payloads/templates_index.ts',

    // ─── CMS preview-token helper (page/template preview only) ──────────────
    'app/helpers/core/preview_token.ts',
    'tests/unit/helpers/core/preview_token.spec.ts',

    // ─── CMS migrations ─────────────────────────────────────────────────────
    'database/migrations/cms',

    // ─── CMS seeders ────────────────────────────────────────────────────────
    'database/seeders/page_seeder.ts',
    'database/seeders/template_seeder.ts',

    // ─── CMS i18n namespaces (page, template, builder) ──────────────────────
    'resources/lang/en/page.json',
    'resources/lang/fr/page.json',
    'resources/lang/en/template.json',
    'resources/lang/fr/template.json',
    'resources/lang/en/builder.json',
    'resources/lang/fr/builder.json',

    // ─── CMS email template (contact form) ──────────────────────────────────
    'resources/views/emails/contact_form_email.edge',

    // ─── CMS route files ────────────────────────────────────────────────────
    'start/routes/cms_admin.routes.ts',
    'start/routes/cms_api.routes.ts',
    'start/routes/cms_public.routes.ts',

    // ─── Transmit integration ───────────────────────────────────────────────
    'start/transmit.ts',
    'config/transmit.ts',
    'config/cms.ts',

    // ─── CMS React subtrees (builder, renderer, pages) ──────────────────────
    'inertia/pages/cms',
    'inertia/components/cms',

    // ─── CMS-only test helpers ──────────────────────────────────────────────
    'tests/helpers/browser/wait_for_builder_ready.ts',

    // ─── CMS test suites ────────────────────────────────────────────────────
    'tests/unit/actions/page',
    'tests/unit/actions/template',
    'tests/unit/models/page',
    'tests/unit/models/page.spec.ts',
    'tests/unit/models/page_translation.spec.ts',
    'tests/unit/models/template',
    'tests/unit/services/page',
    'tests/unit/services/template',
    'tests/unit/validators/page_validator.spec.ts',
    'tests/unit/validators/template_validator.spec.ts',
    'tests/integration/repositories/page_repository.spec.ts',
    'tests/integration/repositories/page_translation_repository.spec.ts',
    'tests/integration/repositories/page_revision_repository.spec.ts',
    'tests/integration/repositories/template_repository.spec.ts',
    'tests/integration/services/page/page_sitemap_collector.spec.ts',
    'tests/integration/routes_structure_cms.spec.ts',
    'tests/browser/builder',
    'tests/browser/template',
    'tests/browser/cms',

    // ─── CMS split-off test files ───────────────────────────────────────────
    'tests/unit/exceptions_cms.spec.ts',
    'tests/unit/actions/cms',
    'tests/unit/services/cms',
    'tests/unit/mails/notifications_cms.spec.ts',
    'tests/unit/validators/builder_validator.spec.ts',
    'tests/unit/validators/contact_validator.spec.ts',
    'tests/functional/cms',
    'tests/helpers/browser/seed_dashboard.ts',

    // ─── Prune pipeline (main-only infrastructure) ──────────────────────────
    'tooling/prune',
    'tests/unit/prune',

    // ─── Generated indexes ──────────────────────────────────────────────────
    // The entire .adonisjs directory is deleted so the pruned tree carries
    // zero CMS references. `npm run dev` regenerates it fresh against the
    // pruned source tree (init hooks + ready hook + Tuyau routesScanned).
    '.adonisjs',
  ],

  rewrites: [
    // ─── config/features.ts — turn the cms flag off ─────────────────────────
    {
      path: 'config/features.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Feature flags',
        '|--------------------------------------------------------------------------',
        '|',
        '| Runtime toggles to enable or disable route modules.',
        '| All features are enabled by default — change a boolean to',
        '| deactivate a module at runtime without touching routing code.',
        '|',
        '| The `inertia` flavor drops the CMS module (page/template/builder): the',
        '| `cms` flag is off and the CMS route registrations are absent from',
        '| `start/routes.ts`.',
        '*/',
        '',
        'export default {',
        '  auth: true,',
        '  settings: true,',
        '  admin: true,',
        '  adminApi: true,',
        '  cms: false,',
        '  maintenance: true,',
        '} as const',
        '',
      ].join('\n'),
    },

    // ─── config/database.ts — drop the CMS migration folder ─────────────────
    {
      path: 'config/database.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/lucid'",
        '',
        'const dbConfig = defineConfig({',
        '  /**',
        '   * Default connection used for all queries.',
        '   */',
        "  connection: 'pg',",
        '',
        '  connections: {',
        '    /**',
        '     * SQLite connection (default).',
        '     */',
        '    sqlite: {',
        "      client: 'better-sqlite3',",
        '',
        '      connection: {',
        '        /**',
        '         * Database file location.',
        '         */',
        "        filename: app.tmpPath('db.sqlite3'),",
        '      },',
        '',
        '      /**',
        '       * Required by Knex for SQLite defaults.',
        '       */',
        '      useNullAsDefault: true,',
        '',
        '      migrations: {',
        '        /**',
        '         * Sort migration files naturally by filename.',
        '         */',
        '        naturalSort: true,',
        '',
        '        /**',
        '         * Paths containing migration files. The `inertia` flavor prunes the',
        '         * CMS module, so `database/migrations/cms` is absent.',
        '         */',
        "        paths: ['database/migrations'],",
        '      },',
        '    },',
        '',
        '    /**',
        '     * PostgreSQL connection.',
        '     * Install package to switch: npm install pg',
        '     */',
        '    pg: {',
        "      client: 'pg',",
        '      connection: {',
        '        host: process.env.PG_HOST,',
        '        port: Number(process.env.PG_PORT || 5432),',
        '        user: process.env.PG_USER,',
        '        password: process.env.PG_PASSWORD,',
        '        database: process.env.PG_DB_NAME,',
        '      },',
        '      migrations: {',
        '        naturalSort: true,',
        "        paths: ['database/migrations'],",
        '      },',
        '      debug: app.inDev,',
        '    },',
        '',
        '    /**',
        '     * MySQL / MariaDB connection.',
        '     * Install package to switch: npm install mysql2',
        '     */',
        '    // mysql: {',
        '    //   client: "mysql2",',
        '    //   connection: {',
        '    //     host: process.env.MYSQL_HOST,',
        '    //     port: Number(process.env.MYSQL_PORT || 3306),',
        '    //     user: process.env.MYSQL_USER,',
        '    //     password: process.env.MYSQL_PASSWORD,',
        '    //     database: process.env.MYSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * Microsoft SQL Server connection.',
        '     * Install package to switch: npm install tedious',
        '     */',
        '    // mssql: {',
        '    //   client: "mssql",',
        '    //   connection: {',
        '    //     server: process.env.MSSQL_SERVER,',
        '    //     port: Number(process.env.MSSQL_PORT || 1433),',
        '    //     user: process.env.MSSQL_USER,',
        '    //     password: process.env.MSSQL_PASSWORD,',
        '    //     database: process.env.MSSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * libSQL (Turso) connection.',
        '     * Install package to switch: npm install @libsql/client',
        '     */',
        '    // libsql: {',
        '    //   client: "libsql",',
        '    //   connection: {',
        '    //     url: process.env.LIBSQL_URL,',
        '    //     authToken: process.env.LIBSQL_AUTH_TOKEN,',
        '    //   },',
        '    //   useNullAsDefault: true,',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '  },',
        '})',
        '',
        'export default dbConfig',
        '',
      ].join('\n'),
    },

    // ─── config/shield.ts — drop the CMS iframe frame-src hosts ─────────────
    {
      path: 'config/shield.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/shield'",
        '',
        '/**',
        ' * CSP configuration for the `inertia` flavor.',
        ' *',
        ' * The CMS `iframe` block (and its `frame-src` host allowlist) is pruned in',
        ' * this flavor, so the CMS-specific imports are gone and the `frame-src`',
        ' * directive falls back to the default origin-only policy.',
        ' */',
        'const shieldConfig = defineConfig({',
        '  /**',
        '   * Configure CSP policies for your app. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csp: {',
        '    /**',
        '     * Enable the Content-Security-Policy header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Report violations without blocking resources in dev/test.',
        '     * Enforce in production.',
        '     */',
        '    reportOnly: app.inDev || app.inTest,',
        '',
        '    /**',
        '     * Per-resource CSP directives.',
        '     */',
        '    directives: {',
        '      // Default: only same-origin',
        '      defaultSrc: ["\'self\'"],',
        '',
        '      // Scripts: self + Vite HMR in dev/test',
        '      scriptSrc: [',
        '        "\'self\'",',
        '        ...(app.inDev || app.inTest ? ["\'unsafe-eval\'", "\'unsafe-inline\'"] : []), // Vite HMR needs these in dev/test',
        '      ],',
        '',
        '      // Styles: self + Tailwind JIT inline styles',
        '      styleSrc: ["\'self\'", "\'unsafe-inline\'"],',
        '',
        '      // Images: self + data: URIs + HTTPS',
        "      imgSrc: [\"'self'\", 'data:', 'https:'],",
        '',
        '      // Fonts: self + data: (for inline fonts)',
        "      fontSrc: [\"'self'\", 'data:'],",
        '',
        '      // Connect: self + SSE + Vite HMR websocket + Sentry',
        '      connectSrc: [',
        '        "\'self\'",',
        "        ...(app.inDev || app.inTest ? ['ws:', 'wss:'] : []), // Vite HMR websocket",
        "        'https://*.sentry.io', // Sentry error reporting",
        '      ],',
        '',
        '      // Frames: default to same-origin only — the CMS iframe block is pruned.',
        '      frameSrc: ["\'self\'"],',
        '',
        '      // Frames: deny (xFrame also set to SAMEORIGIN)',
        '      frameAncestors: ["\'none\'"],',
        '',
        '      // Forms: self only',
        '      formAction: ["\'self\'"],',
        '',
        '      // Base URI: self',
        '      baseUri: ["\'self\'"],',
        '',
        '      // Object/embed: none',
        '      objectSrc: ["\'none\'"],',
        '',
        '      // Media: self + external direct video files (video block)',
        "      mediaSrc: [\"'self'\", 'https:'],",
        '',
        '      // Workers: self',
        '      workerSrc: ["\'self\'"],',
        '',
        '      // Manifest: self',
        '      manifestSrc: ["\'self\'"],',
        '    },',
        '  },',
        '',
        '  /**',
        '   * Configure CSRF protection options. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csrf: {',
        '    /**',
        '     * Enable CSRF token verification for state-changing requests.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Routes to exclude from CSRF checks. Useful for external webhooks or',
        '     * API endpoints. Patterns match `ctx.route.pattern` exactly (no glob),',
        '     * hence the function form.',
        '     *',
        '     * `/api/v1/*` is the token-guarded REST API: Bearer-token requests carry',
        '     * no cookies, so they are not exposed to CSRF. Session-authenticated API',
        '     * routes (`/api/admin/*`, `/api/settings/*`) keep full CSRF protection.',
        '     */',
        '    exceptRoutes: (ctx) =>',
        "      ctx.route !== undefined && ctx.route.pattern.replace(/^\\//, '').startsWith('api/v1/'),",
        '',
        '    /**',
        '     * Expose an encrypted XSRF-TOKEN cookie for frontend HTTP clients.',
        '     */',
        '    enableXsrfCookie: true,',
        '',
        '    /**',
        '     * HTTP methods protected by CSRF validation.',
        '     */',
        "    methods: ['POST', 'PUT', 'PATCH', 'DELETE'],",
        '  },',
        '',
        '  /**',
        '   * Control how your website should be embedded inside',
        '   * iframes.',
        '   */',
        '  xFrame: {',
        '    /**',
        '     * Enable the X-Frame-Options header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Block all framing attempts. Default value is DENY.',
        '     */',
        "    action: 'SAMEORIGIN',",
        '  },',
        '',
        '  /**',
        '   * Force browser to always use HTTPS.',
        '   */',
        '  hsts: {',
        '    /**',
        '     * Enable the Strict-Transport-Security header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * HSTS policy duration remembered by browsers.',
        '     */',
        "    maxAge: '180 days',",
        '  },',
        '',
        '  /**',
        '   * Disable browsers from sniffing content types and rely only',
        '   * on the response content-type header.',
        '   */',
        '  contentTypeSniffing: {',
        '    /**',
        '     * Enable X-Content-Type-Options: nosniff.',
        '     */',
        '    enabled: true,',
        '  },',
        '})',
        '',
        'export default shieldConfig',
        '',
      ].join('\n'),
    },

    // ─── start/routes.ts — drop CMS, keep API, add the front routes ─────────
    {
      path: 'start/routes.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Routes file',
        '|--------------------------------------------------------------------------',
        '|',
        '| Route module index — each domain registers its own routes.',
        '| Feature flags in config/features.ts gate each module at runtime.',
        '|',
        '| The `inertia` flavor ships a hand-written front: the home page and error',
        '| pages are served by `front.*` controllers registered here, alongside the',
        '| core SEO endpoints and the admin back-office.',
        '*/',
        '',
        "import features from '#config/features'",
        "import router from '@adonisjs/core/services/router'",
        "import { enabledAuthGuards } from '#config/auth'",
        "import { registerAuthRoutes } from '#start/routes/auth.routes'",
        "import { registerSettingsRoutes } from '#start/routes/settings.routes'",
        "import { registerAdminRoutes } from '#start/routes/admin.routes'",
        "import { registerAdminApiRoutes } from '#start/routes/admin_api.routes'",
        "import { registerCorePublicRoutes } from '#start/routes/core_public.routes'",
        "import { registerFrontRoutes } from '#start/routes/front.routes'",
        "import { registerApiRoutes } from '#start/routes/api.routes'",
        "import { registerHealthRoutes } from '#start/routes/health.routes'",
        "import { middleware } from '#start/kernel'",
        '',
        '// Health routes are outside maintenance middleware (liveness/readiness probes)',
        'registerHealthRoutes()',
        '',
        '// Wrap all feature routes with maintenance middleware',
        '// Health routes are registered separately above (outside this wrapper)',
        '',
        'router',
        '  .group(() => {',
        '    // Core SEO endpoints (sitemap.xml, robots.txt) — flavor-independent.',
        '    registerCorePublicRoutes()',
        '',
        '    // Hand-written front (home + error pages) — replaces the CMS public front.',
        '    registerFrontRoutes()',
        '',
        '    if (features.auth) registerAuthRoutes()',
        '    if (features.settings) registerSettingsRoutes()',
        '    if (features.admin) registerAdminRoutes()',
        '    if (features.adminApi) registerAdminApiRoutes()',
        '',
        '    // Token-guarded REST API — only when the `api` guard is enabled.',
        '    if (enabledAuthGuards.api) registerApiRoutes()',
        '  })',
        '  .use(features.maintenance ? middleware.maintenance() : [])',
        '',
      ].join('\n'),
    },

    // ─── start/events.ts — drop the CMS contact-form listener ───────────────
    {
      path: 'start/events.ts',
      content: [
        "import emitter from '@adonisjs/core/services/emitter'",
        "import { events } from '#generated/events'",
        "import { listeners } from '#generated/listeners'",
        '',
        "emitter.on(events.auth.UserRegistered, [listeners.auth.SendVerificationEmail, 'handle'])",
        '',
        "emitter.on(events.auth.ForgotPassword, [listeners.auth.SendForgotPasswordEmail, 'handle'])",
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailNotificationEmail,',
        "  'handle',",
        '])',
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailConfirmationEmail,',
        "  'handle',",
        '])',
        '',
        "emitter.on(events.admin.InviteUser, [listeners.admin.SendInvitationEmail, 'handle'])",
        '',
      ].join('\n'),
    },

    // ─── start/nav.ts — drop the page + template nav entries ────────────────
    {
      path: 'start/nav.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Admin navigation composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the admin navigation entries of every domain existing in this',
        '| flavor of the application, in sidebar order. This file is part of the',
        "| composition set that flavor manifests may rewrite: remove a domain's",
        '| registration and its entries disappear from the admin sidebar.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { NavRegistry } from '#services/core/nav_registry'",
        "import { coreNavEntries } from '#services/core/core_nav'",
        "import { authNavEntries } from '#services/auth/auth_nav'",
        "import { fileNavEntries } from '#services/file/file_nav'",
        "import { maintenanceNavEntries } from '#services/maintenance/maintenance_nav'",
        "import { loggingNavEntries } from '#services/logging/logging_nav'",
        '',
        'app.container.singleton(NavRegistry, () => new NavRegistry())',
        '',
        'const registry = await app.container.make(NavRegistry)',
        '',
        "registry.register('core', coreNavEntries)",
        "registry.register('file', fileNavEntries)",
        "registry.register('auth', authNavEntries)",
        "registry.register('maintenance', maintenanceNavEntries)",
        "registry.register('logging', loggingNavEntries)",
        '',
      ].join('\n'),
    },

    // ─── start/dashboard.ts — drop the page + template collectors ───────────
    {
      path: 'start/dashboard.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Dashboard composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the dashboard section collectors of every domain existing in',
        '| this flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its section disappears from the admin dashboard.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { DashboardRegistry } from '#services/core/dashboard_registry'",
        "import { AuthDashboardCollector } from '#services/auth/auth_dashboard_collector'",
        "import { FileDashboardCollector } from '#services/file/file_dashboard_collector'",
        '',
        'app.container.singleton(DashboardRegistry, () => new DashboardRegistry())',
        '',
        'const registry = await app.container.make(DashboardRegistry)',
        '',
        "registry.register('auth', () => app.container.make(AuthDashboardCollector))",
        "registry.register('file', () => app.container.make(FileDashboardCollector))",
        '',
      ].join('\n'),
    },

    // ─── start/container.ts — drop the builder session binding ──────────────
    {
      path: 'start/container.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { BackupEngine } from '#services/backup/backup_engine'",
        "import { CacheService } from '#services/cache/cache_service'",
        "import { RedisCacheDriver } from '#services/cache/drivers/redis_cache_driver'",
        "import { LogService } from '#services/logging/log_service'",
        "import { MaintenanceService } from '#services/maintenance/maintenance_service'",
        '',
        '/**',
        ' * IoC container bindings.',
        ' *',
        ' * Singleton services are instantiated exactly once per process and reused',
        ' * across every request — which is what makes in-flight state (locks,',
        ' * sessions) work correctly without serialising to a database on every call.',
        ' * Factory bindings are re-created on each resolution with runtime arguments',
        ' * supplied via {@link app.container.make}.',
        ' *',
        " * Add this file to `adonisrc.ts` preloads if it isn't already:",
        ' *',
        ' * @example',
        ' * // adonisrc.ts',
        ' * preloads: [',
        " *   () => import('#start/container'),",
        ' * ]',
        ' */',
        '',
        '// ─── BackupEngine (factory) ────────────────────────────────────────────',
        '',
        '/**',
        ' * Factory binding for {@link BackupEngine} so that callers can resolve it',
        ' * through the container instead of using `new`. Runtime arguments',
        ' * (`strategyType`, `tempDir`) are supplied at resolution time which keeps',
        ' * the strategy dynamic while still being mockable in tests via',
        ' * {@link app.container.swap}.',
        ' *',
        ' * @example',
        " * const engine = await app.container.make(BackupEngine, ['full', 'storage/temp/backups'])",
        ' */',
        'app.container.bind(BackupEngine, async (resolver, runtimeValues) => {',
        '  const [strategyType, tempDir] = runtimeValues ?? []',
        '  const logService = await resolver.make(LogService)',
        '  return new BackupEngine(strategyType, tempDir, logService)',
        '})',
        '',
        '// ─── CacheService (singleton) ──────────────────────────────────────────',
        '',
        '/**',
        ' * The root `CacheService` backed by Redis.',
        ' * Inject or resolve via the container anywhere in the app:',
        ' *',
        ' * @example',
        ' * // In a service or controller',
        ' * const cache = await app.container.make(CacheService)',
        ' */',
        'app.container.singleton(CacheService, () => {',
        '  const driver = new RedisCacheDriver()',
        '  return new CacheService(driver)',
        '})',
        '',
        '// ─── MaintenanceService (singleton) ────────────────────────────────────',
        '',
        '/**',
        ' * Maintenance service singleton.',
        ' * Handles Redis + memory fallback for maintenance mode configuration.',
        ' * Initializes memory fallback on first resolution.',
        ' */',
        'app.container.singleton(MaintenanceService, async () => {',
        '  const service = MaintenanceService.getInstance()',
        '  await service.initializeMemoryFallback()',
        '  return service',
        '})',
        '',
      ].join('\n'),
    },

    // ─── start/sitemap.ts — drop the page contributor (routes only) ─────────
    {
      path: 'start/sitemap.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Sitemap composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the sitemap contributors of every domain existing in this',
        '| flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its URLs disappear from `sitemap.xml`.',
        '|',
        '| The route collector is always present (hand-written `front.*` routes',
        '| exist in every flavor with a public front). The page collector is',
        '| CMS-specific and is removed by the `inertia` flavor manifest.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { SitemapRegistry } from '#services/core/sitemap_registry'",
        "import { RouteSitemapCollector } from '#services/core/route_sitemap_collector'",
        '',
        'app.container.singleton(SitemapRegistry, () => new SitemapRegistry())',
        '',
        'const registry = await app.container.make(SitemapRegistry)',
        '',
        "registry.register('routes', () => app.container.make(RouteSitemapCollector))",
        '',
      ].join('\n'),
    },

    // ─── adonisrc.ts — drop the Transmit provider + preload ─────────────────
    {
      path: 'adonisrc.ts',
      content: [
        "import { indexPages } from '@adonisjs/inertia'",
        "import { indexEntities } from '@adonisjs/core'",
        "import { defineConfig } from '@adonisjs/core/app'",
        "import { generateRegistry } from '@tuyau/core/hooks'",
        '',
        'export default defineConfig({',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Experimental flags',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | The following features will be enabled by default in the next major',
        '  | release of AdonisJS. You can opt into them today to avoid any breaking',
        '  | changes during upgrade.',
        '  |',
        '  */',
        '  experimental: {},',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Commands',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of ace commands to register from packages. The application',
        '  | commands will be scanned automatically from the "./commands" directory.',
        '  |',
        '  */',
        '  commands: [',
        "    () => import('@adonisjs/core/commands'),",
        "    () => import('@adonisjs/lucid/commands'),",
        "    () => import('@adonisjs/session/commands'),",
        "    () => import('@adonisjs/inertia/commands'),",
        "    () => import('@adonisjs/mail/commands'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Directories',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  */',
        '  directories: {',
        "    httpControllers: 'app/http/controllers',",
        "    transformers: 'app/data/transformers',",
        "    middleware: 'app/http/middleware',",
        "    services: 'app/domain/services',",
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Service providers',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of service providers to import and register when booting the',
        '  | application',
        '  |',
        '  */',
        '  providers: [',
        "    () => import('@adonisjs/core/providers/app_provider'),",
        "    () => import('@adonisjs/core/providers/hash_provider'),",
        '    {',
        "      file: () => import('@adonisjs/core/providers/repl_provider'),",
        "      environment: ['repl', 'test'],",
        '    },',
        "    () => import('@adonisjs/core/providers/vinejs_provider'),",
        "    () => import('@adonisjs/core/providers/edge_provider'),",
        "    () => import('@adonisjs/session/session_provider'),",
        "    () => import('@adonisjs/vite/vite_provider'),",
        "    () => import('@adonisjs/shield/shield_provider'),",
        "    () => import('@adonisjs/static/static_provider'),",
        "    () => import('@adonisjs/lucid/database_provider'),",
        "    () => import('@adonisjs/cors/cors_provider'),",
        "    () => import('@adonisjs/inertia/inertia_provider'),",
        "    () => import('@adonisjs/auth/auth_provider'),",
        "    () => import('#providers/api_provider'),",
        "    () => import('@adonisjs/redis/redis_provider'),",
        "    () => import('@rlanz/sentry/provider'),",
        "    () => import('@adonisjs/i18n/i18n_provider'),",
        "    () => import('@adonisjs/ally/ally_provider'),",
        "    () => import('@adonisjs/mail/mail_provider'),",
        "    () => import('@adonisjs/drive/drive_provider'),",
        "    () => import('@adonisjs/limiter/limiter_provider'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Preloads',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of modules to import before starting the application.',
        '  |',
        '  */',
        '  preloads: [',
        "    () => import('#start/routes'),",
        "    () => import('#start/kernel'),",
        "    () => import('#start/validator'),",
        "    () => import('#start/events'),",
        "    () => import('#start/container'),",
        "    () => import('#start/dashboard'),",
        "    () => import('#start/sitemap'),",
        "    () => import('#start/nav'),",
        "    () => import('#start/extensions'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Tests',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of test suites to organize tests by their type. Feel free to',
        '  | remove and add additional suites.',
        '  |',
        '  */',
        '  tests: {',
        '    suites: [',
        '      {',
        "        files: ['tests/unit/**/*.spec.{ts,js}'],",
        "        name: 'unit',",
        '        timeout: 2000,',
        '      },',
        '      {',
        "        files: ['tests/integration/**/*.spec.{ts,js}'],",
        "        name: 'integration',",
        '        timeout: 5000,',
        '      },',
        '      {',
        "        files: ['tests/functional/**/*.spec.{ts,js}'],",
        "        name: 'functional',",
        '        timeout: 30000,',
        '      },',
        '      {',
        "        files: ['tests/browser/**/*.spec.{ts,js}'],",
        "        name: 'browser',",
        '        timeout: 300000,',
        '      },',
        '    ],',
        '    forceExit: false,',
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Metafiles',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | A collection of files you want to copy to the build folder when',
        '  | creating the production build.',
        '  |',
        '  */',
        '  metaFiles: [',
        '    {',
        "      pattern: 'resources/views/**/*.edge',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'public/**',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'resources/lang/**/*.{json,yaml,yml}',",
        '      reloadServer: false,',
        '    },',
        '  ],',
        '',
        '  hooks: {',
        '    init: [',
        '      indexEntities({',
        '        transformers: {',
        '          enabled: true,',
        '          withSharedProps: true,',
        "          source: 'app/data/transformers',",
        "          importAlias: '#transformers',",
        "          glob: ['**\\/*transformer.ts'],",
        '        },',
        '        controllers: {',
        '          enabled: true,',
        "          source: 'app/http/controllers',",
        "          importAlias: '#controllers',",
        "          glob: ['**\\/*_controller.ts'],",
        '        },',
        '      }),',
        "      indexPages({ framework: 'react' }),",
        '      generateRegistry(),',
        '    ],',
        "    buildStarting: [() => import('@adonisjs/vite/build_hook')],",
        '  },',
        '})',
        '',
      ].join('\n'),
    },
  ],

  dependencies: {
    packages: ['@adonisjs/transmit', '@adonisjs/transmit-client'],
  },
}

export default inertiaManifest
