/**
 * `inertia` flavor manifest.
 *
 * Derives the hand-written-Inertia flavor from `main`: keeps the full admin
 * back-office (users, roles, permissions, files, logs, maintenance, settings,
 * dashboard) and the complete auth flow, prunes the `page` and `template`
 * domains and Transmit entirely, and ships a minimal hand-written front
 * (a blank home page and error pages, each served by its own `front.*`
 * controller).
 *
 * The delete inventory mirrors ADR-0001's CMS delete map: the whole `app/cms/`
 * module, every smeared CMS path outside it (controllers, transformers,
 * events, listeners, mails, i18n payload helpers, migrations, i18n, seeders,
 * tests), the Transmit integration, and the builder/template React subtrees.
 * The rewrites drop the CMS and Transmit registrations from the allowlisted
 * composition files and turn the `cms` feature flag off.
 *
 * Applied by {@link '../engine'} via
 * `node --import @poppinss/ts-exec tooling/prune/apply.ts inertia`.
 */
import type { FlavorManifest } from '#prune/types'

const inertiaManifest: FlavorManifest = {
  flavor: 'inertia',

  delete: [
    // ─── CMS module (page, template, builder) ───────────────────────────────
    'app/cms',

    // ─── CMS controllers (page + template) ──────────────────────────────────
    'app/http/controllers/page',
    'app/http/controllers/template',
    'app/http/rest/pages_resource.ts',
    'app/http/rest/templates_resource.ts',

    // ─── CMS transformers (page + template) ─────────────────────────────────
    'app/data/transformers/page',
    'app/data/transformers/template',

    // ─── CMS events and listeners ───────────────────────────────────────────
    'app/events/page',
    'app/listeners/page',

    // ─── CMS mail (contact form) ────────────────────────────────────────────
    'app/mails/page',

    // ─── CMS i18n payload helpers ───────────────────────────────────────────
    'app/helpers/i18n_payloads/pages_create.ts',
    'app/helpers/i18n_payloads/pages_index.ts',
    'app/helpers/i18n_payloads/pages_show.ts',
    'app/helpers/i18n_payloads/page_editor.ts',
    'app/helpers/i18n_payloads/page_revisions.ts',
    'app/helpers/i18n_payloads/templates_edit.ts',
    'app/helpers/i18n_payloads/templates_index.ts',

    // ─── CMS preview-token helper (page/template preview only) ──────────────
    'app/helpers/core/preview_token.ts',
    'tests/unit/helpers/core/preview_token.spec.ts',
    'tests/unit/helpers/i18n_payloads_cms.spec.ts',
    'commands/cms_normalize_migration_names.ts',

    // ─── CMS migrations ─────────────────────────────────────────────────────
    'database/migrations/cms',

    // ─── CMS seeders ────────────────────────────────────────────────────────
    'database/seeders/page_seeder.ts',
    'database/seeders/template_seeder.ts',

    // ─── CMS i18n namespaces (page, template, builder) ──────────────────────
    'resources/lang/en/page.json',
    'resources/lang/fr/page.json',
    'resources/lang/en/template.json',
    'resources/lang/fr/template.json',
    'resources/lang/en/builder.json',
    'resources/lang/fr/builder.json',

    // ─── CMS email template (contact form) ──────────────────────────────────
    'resources/views/emails/contact_form_email.edge',

    // ─── CMS route files ────────────────────────────────────────────────────
    'start/routes/cms_admin.routes.ts',
    'start/routes/cms_public.routes.ts',
    'start/routes/cms_rest_api.routes.ts',

    // ─── Transmit integration ───────────────────────────────────────────────
    'start/transmit.ts',
    'config/transmit.ts',
    'config/cms.ts',

    // ─── CMS React subtrees (builder, renderer, pages) ──────────────────────
    'inertia/pages/cms',
    'inertia/components/cms',

    // ─── CMS-only test helpers ──────────────────────────────────────────────
    'tests/helpers/browser/wait_for_builder_ready.ts',

    // ─── CMS test suites ────────────────────────────────────────────────────
    'tests/unit/actions/page',
    'tests/unit/actions/template',
    'tests/unit/models/page',
    'tests/unit/models/page.spec.ts',
    'tests/unit/models/page_translation.spec.ts',
    'tests/unit/models/template',
    'tests/unit/services/page',
    'tests/unit/services/template',
    'tests/unit/validators/page_validator.spec.ts',
    'tests/unit/validators/template_validator.spec.ts',
    'tests/integration/repositories/page_repository.spec.ts',
    'tests/integration/repositories/page_translation_repository.spec.ts',
    'tests/integration/repositories/page_revision_repository.spec.ts',
    'tests/integration/repositories/template_repository.spec.ts',
    'tests/integration/services/page/page_sitemap_collector.spec.ts',
    'tests/integration/routes_structure_cms.spec.ts',
    'tests/browser/builder',
    'tests/browser/template',
    'tests/browser/cms',

    // ─── CMS split-off test files ───────────────────────────────────────────
    'tests/unit/exceptions_cms.spec.ts',
    'tests/unit/actions/cms',
    'tests/unit/services/cms',
    'tests/unit/mails/notifications_cms.spec.ts',
    'tests/unit/validators/builder_validator.spec.ts',
    'tests/unit/validators/contact_validator.spec.ts',
    'tests/functional/cms',
    'tests/helpers/browser/seed_dashboard.ts',

    // ─── Prune pipeline (main-only infrastructure) ──────────────────────────
    'tooling/prune',
    'tests/unit/prune',

    // ─── Generated indexes ──────────────────────────────────────────────────
    // The entire .adonisjs directory is deleted so the pruned tree carries
    // zero CMS references. `npm run dev` regenerates it fresh against the
    // pruned source tree (init hooks + ready hook + Tuyau routesScanned).
    '.adonisjs',
  ],

  rewrites: [
    // ─── config/features.ts — turn the cms flag off ─────────────────────────
    {
      path: 'config/features.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Feature flags',
        '|--------------------------------------------------------------------------',
        '|',
        '| Runtime toggles to enable or disable route modules.',
        '| All features are enabled by default — change a boolean to',
        '| deactivate a module at runtime without touching routing code.',
        '|',
        '| The `inertia` flavor drops the CMS module (page/template/builder): the',
        '| `cms` flag is off and the CMS route registrations are absent from',
        '| `start/routes.ts`.',
        '*/',
        '',
        'export default {',
        '  auth: true,',
        '  settings: true,',
        '  admin: true,',
        '  adminApi: true,',
        '  cms: false,',
        '  maintenance: true,',
        '} as const',
        '',
      ].join('\n'),
    },

    // ─── config/database.ts — drop the CMS migration folder ─────────────────
    {
      path: 'config/database.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/lucid'",
        '',
        'const dbConfig = defineConfig({',
        '  /**',
        '   * Default connection used for all queries.',
        '   */',
        "  connection: 'pg',",
        '',
        '  connections: {',
        '    /**',
        '     * SQLite connection (default).',
        '     */',
        '    sqlite: {',
        "      client: 'better-sqlite3',",
        '',
        '      connection: {',
        '        /**',
        '         * Database file location.',
        '         */',
        "        filename: app.tmpPath('db.sqlite3'),",
        '      },',
        '',
        '      /**',
        '       * Required by Knex for SQLite defaults.',
        '       */',
        '      useNullAsDefault: true,',
        '',
        '      migrations: {',
        '        /**',
        '         * Sort migration files naturally by filename.',
        '         */',
        '        naturalSort: true,',
        '',
        '        /**',
        '         * Paths containing migration files. The `inertia` flavor prunes the',
        '         * CMS module, so `database/migrations/cms` is absent.',
        '         */',
        "        paths: ['database/migrations'],",
        '      },',
        '    },',
        '',
        '    /**',
        '     * PostgreSQL connection.',
        '     * Install package to switch: npm install pg',
        '     */',
        '    pg: {',
        "      client: 'pg',",
        '      connection: {',
        '        host: process.env.PG_HOST,',
        '        port: Number(process.env.PG_PORT || 5432),',
        '        user: process.env.PG_USER,',
        '        password: process.env.PG_PASSWORD,',
        '        database: process.env.PG_DB_NAME,',
        '      },',
        '      migrations: {',
        '        naturalSort: true,',
        "        paths: ['database/migrations'],",
        '      },',
        '      debug: app.inDev,',
        '    },',
        '',
        '    /**',
        '     * MySQL / MariaDB connection.',
        '     * Install package to switch: npm install mysql2',
        '     */',
        '    // mysql: {',
        '    //   client: "mysql2",',
        '    //   connection: {',
        '    //     host: process.env.MYSQL_HOST,',
        '    //     port: Number(process.env.MYSQL_PORT || 3306),',
        '    //     user: process.env.MYSQL_USER,',
        '    //     password: process.env.MYSQL_PASSWORD,',
        '    //     database: process.env.MYSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * Microsoft SQL Server connection.',
        '     * Install package to switch: npm install tedious',
        '     */',
        '    // mssql: {',
        '    //   client: "mssql",',
        '    //   connection: {',
        '    //     server: process.env.MSSQL_SERVER,',
        '    //     port: Number(process.env.MSSQL_PORT || 1433),',
        '    //     user: process.env.MSSQL_USER,',
        '    //     password: process.env.MSSQL_PASSWORD,',
        '    //     database: process.env.MSSQL_DB_NAME,',
        '    //   },',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '',
        '    /**',
        '     * libSQL (Turso) connection.',
        '     * Install package to switch: npm install @libsql/client',
        '     */',
        '    // libsql: {',
        '    //   client: "libsql",',
        '    //   connection: {',
        '    //     url: process.env.LIBSQL_URL,',
        '    //     authToken: process.env.LIBSQL_AUTH_TOKEN,',
        '    //   },',
        '    //   useNullAsDefault: true,',
        '    //   migrations: {',
        '    //     naturalSort: true,',
        '    //     paths: ["database/migrations"],',
        '    //   },',
        '    //   debug: app.inDev,',
        '    // },',
        '  },',
        '})',
        '',
        'export default dbConfig',
        '',
      ].join('\n'),
    },

    // ─── config/shield.ts — drop the CMS iframe frame-src hosts ─────────────
    {
      path: 'config/shield.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { defineConfig } from '@adonisjs/shield'",
        '',
        '/**',
        ' * CSP configuration for the `inertia` flavor.',
        ' *',
        ' * The CMS `iframe` block (and its `frame-src` host allowlist) is pruned in',
        ' * this flavor, so the CMS-specific imports are gone and the `frame-src`',
        ' * directive falls back to the default origin-only policy.',
        ' */',
        'const shieldConfig = defineConfig({',
        '  /**',
        '   * Configure CSP policies for your app. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csp: {',
        '    /**',
        '     * Enable the Content-Security-Policy header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Report violations without blocking resources in dev/test.',
        '     * Enforce in production.',
        '     */',
        '    reportOnly: app.inDev || app.inTest,',
        '',
        '    /**',
        '     * Per-resource CSP directives.',
        '     */',
        '    directives: {',
        '      // Default: only same-origin',
        '      defaultSrc: ["\'self\'"],',
        '',
        '      // Scripts: self + Vite HMR in dev/test',
        '      scriptSrc: [',
        '        "\'self\'",',
        '        ...(app.inDev || app.inTest ? ["\'unsafe-eval\'", "\'unsafe-inline\'"] : []), // Vite HMR needs these in dev/test',
        '      ],',
        '',
        '      // Styles: self + Tailwind JIT inline styles',
        '      styleSrc: ["\'self\'", "\'unsafe-inline\'"],',
        '',
        '      // Images: self + data: URIs + HTTPS',
        "      imgSrc: [\"'self'\", 'data:', 'https:'],",
        '',
        '      // Fonts: self + data: (for inline fonts)',
        "      fontSrc: [\"'self'\", 'data:'],",
        '',
        '      // Connect: self + SSE + Vite HMR websocket + Sentry',
        '      connectSrc: [',
        '        "\'self\'",',
        "        ...(app.inDev || app.inTest ? ['ws:', 'wss:'] : []), // Vite HMR websocket",
        "        'https://*.sentry.io', // Sentry error reporting",
        '      ],',
        '',
        '      // Frames: default to same-origin only — the CMS iframe block is pruned.',
        '      frameSrc: ["\'self\'"],',
        '',
        '      // Frames: deny (xFrame also set to SAMEORIGIN)',
        '      frameAncestors: ["\'none\'"],',
        '',
        '      // Forms: self only',
        '      formAction: ["\'self\'"],',
        '',
        '      // Base URI: self',
        '      baseUri: ["\'self\'"],',
        '',
        '      // Object/embed: none',
        '      objectSrc: ["\'none\'"],',
        '',
        '      // Media: self + external direct video files (video block)',
        "      mediaSrc: [\"'self'\", 'https:'],",
        '',
        '      // Workers: self',
        '      workerSrc: ["\'self\'"],',
        '',
        '      // Manifest: self',
        '      manifestSrc: ["\'self\'"],',
        '    },',
        '  },',
        '',
        '  /**',
        '   * Configure CSRF protection options. Refer documentation',
        '   * to learn more.',
        '   */',
        '  csrf: {',
        '    /**',
        '     * Enable CSRF token verification for state-changing requests.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Routes to exclude from CSRF checks. Useful for external webhooks or',
        '     * API endpoints. Patterns match `ctx.route.pattern` exactly (no glob),',
        '     * hence the function form.',
        '     *',
        '     * `/api/v1/*` is the token-guarded REST API: Bearer-token requests carry',
        '     * no cookies, so they are not exposed to CSRF. Session-authenticated API',
        '     * routes (`/api/admin/*`, `/api/settings/*`) keep full CSRF protection.',
        '     */',
        '    exceptRoutes: (ctx) =>',
        "      ctx.route !== undefined && ctx.route.pattern.replace(/^\\//, '').startsWith('api/v1/'),",
        '',
        '    /**',
        '     * Expose an encrypted XSRF-TOKEN cookie for frontend HTTP clients.',
        '     */',
        '    enableXsrfCookie: true,',
        '',
        '    /**',
        '     * HTTP methods protected by CSRF validation.',
        '     */',
        "    methods: ['POST', 'PUT', 'PATCH', 'DELETE'],",
        '  },',
        '',
        '  /**',
        '   * Control how your website should be embedded inside',
        '   * iframes.',
        '   */',
        '  xFrame: {',
        '    /**',
        '     * Enable the X-Frame-Options header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * Block all framing attempts. Default value is DENY.',
        '     */',
        "    action: 'SAMEORIGIN',",
        '  },',
        '',
        '  /**',
        '   * Force browser to always use HTTPS.',
        '   */',
        '  hsts: {',
        '    /**',
        '     * Enable the Strict-Transport-Security header.',
        '     */',
        '    enabled: true,',
        '',
        '    /**',
        '     * HSTS policy duration remembered by browsers.',
        '     */',
        "    maxAge: '180 days',",
        '  },',
        '',
        '  /**',
        '   * Disable browsers from sniffing content types and rely only',
        '   * on the response content-type header.',
        '   */',
        '  contentTypeSniffing: {',
        '    /**',
        '     * Enable X-Content-Type-Options: nosniff.',
        '     */',
        '    enabled: true,',
        '  },',
        '})',
        '',
        'export default shieldConfig',
        '',
      ].join('\n'),
    },

    // ─── start/routes.ts — drop CMS, keep API, add the front routes ─────────
    {
      path: 'start/routes.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Routes file',
        '|--------------------------------------------------------------------------',
        '|',
        '| Route module index — each domain registers its own routes.',
        '| Feature flags in config/features.ts gate each module at runtime.',
        '|',
        '| The `inertia` flavor ships a hand-written front: the home page and error',
        '| pages are served by `front.*` controllers registered here, alongside the',
        '| core SEO endpoints and the admin back-office.',
        '*/',
        '',
        "import features from '#config/features'",
        "import router from '@adonisjs/core/services/router'",
        "import { enabledAuthGuards } from '#config/auth'",
        "import { registerAuthRoutes } from '#start/routes/auth.routes'",
        "import { registerSettingsRoutes } from '#start/routes/settings.routes'",
        "import { registerAdminRoutes } from '#start/routes/admin.routes'",
        "import { registerAdminRestApiRoutes } from '#start/routes/admin_rest_api.routes'",
        "import { registerCorePublicRoutes } from '#start/routes/core_public.routes'",
        "import { registerFrontRoutes } from '#start/routes/front.routes'",
        "import { registerApiRoutes } from '#start/routes/api.routes'",
        "import { registerHealthRoutes } from '#start/routes/health.routes'",
        "import { middleware } from '#start/kernel'",
        '',
        '// Health routes are outside maintenance middleware (liveness/readiness probes)',
        'registerHealthRoutes()',
        '',
        '// Wrap all feature routes with maintenance middleware',
        '// Health routes are registered separately above (outside this wrapper)',
        '',
        'router',
        '  .group(() => {',
        '    // Core SEO endpoints (sitemap.xml, robots.txt) — flavor-independent.',
        '    registerCorePublicRoutes()',
        '',
        '    // Hand-written front (home + error pages) — replaces the CMS public front.',
        '    registerFrontRoutes()',
        '',
        '    if (features.auth) registerAuthRoutes()',
        '    if (features.settings) registerSettingsRoutes()',
        '    if (features.admin) registerAdminRoutes()',
        '    if (features.adminApi) registerAdminRestApiRoutes()',
        '',
        '    // Token-guarded identity/register REST API — only when the `api` guard',
        '    // is enabled and the `adminApi` surface is on.',
        '    if (features.adminApi && enabledAuthGuards.api) registerApiRoutes()',
        '  })',
        '  .use(features.maintenance ? middleware.maintenance() : [])',
        '',
      ].join('\n'),
    },

    // ─── start/events.ts — drop the CMS contact-form listener ───────────────
    {
      path: 'start/events.ts',
      content: [
        "import emitter from '@adonisjs/core/services/emitter'",
        "import { events } from '#generated/events'",
        "import { listeners } from '#generated/listeners'",
        '',
        "emitter.on(events.auth.UserRegistered, [listeners.auth.SendVerificationEmail, 'handle'])",
        '',
        "emitter.on(events.auth.ForgotPassword, [listeners.auth.SendForgotPasswordEmail, 'handle'])",
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailNotificationEmail,',
        "  'handle',",
        '])',
        '',
        'emitter.on(events.account.InitiateEmailChange, [',
        '  listeners.account.SendChangeEmailConfirmationEmail,',
        "  'handle',",
        '])',
        '',
        "emitter.on(events.admin.InviteUser, [listeners.admin.SendInvitationEmail, 'handle'])",
        '',
      ].join('\n'),
    },

    // ─── start/nav.ts — drop the page + template nav entries ────────────────
    {
      path: 'start/nav.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Admin navigation composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the admin navigation entries of every domain existing in this',
        '| flavor of the application, in sidebar order. This file is part of the',
        "| composition set that flavor manifests may rewrite: remove a domain's",
        '| registration and its entries disappear from the admin sidebar.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { NavRegistry } from '#services/core/nav_registry'",
        "import { coreNavEntries } from '#services/core/core_nav'",
        "import { authNavEntries } from '#services/auth/auth_nav'",
        "import { fileNavEntries } from '#services/file/file_nav'",
        "import { maintenanceNavEntries } from '#services/maintenance/maintenance_nav'",
        "import { loggingNavEntries } from '#services/logging/logging_nav'",
        '',
        'app.container.singleton(NavRegistry, () => new NavRegistry())',
        '',
        'const registry = await app.container.make(NavRegistry)',
        '',
        "registry.register('core', coreNavEntries)",
        "registry.register('file', fileNavEntries)",
        "registry.register('auth', authNavEntries)",
        "registry.register('maintenance', maintenanceNavEntries)",
        "registry.register('logging', loggingNavEntries)",
        '',
      ].join('\n'),
    },

    // ─── start/permissions.ts — drop the page + template catalogs ───────────
    {
      path: 'start/permissions.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| System Permission Catalog',
        '|--------------------------------------------------------------------------',
        '|',
        '| The composed list of system permission slugs for this flavor. Every',
        '| domain owns its own catalog const in `{domain}_permissions.ts` (see',
        '| `app/domain/services/*` and `app/cms/domain/services/*`); this file',
        '| composes those per-domain catalogs into the single matrix the permission',
        '| seeder persists. Adding or renaming a permission only touches that',
        "| domain's catalog file.",
        '|',
        '| The `permissionCatalog` object also drives the `PermissionSlug` union of',
        '| this flavor: the catalog is the single source of both the persisted slug',
        '| values and the slug type.',
        '|',
        '| The composed catalog finally yields the `permissions` identity map — one',
        '| camelCase key per slug, mapped to the raw slug string — which route',
        '| guards, nav entries and ability checks reference instead of raw literals.',
        '|',
        '*/',
        '',
        "import { corePermissionCatalog, coreRoleSlugs } from '#services/core/core_permissions'",
        "import { authPermissionCatalog } from '#services/auth/auth_permissions'",
        "import { filePermissionCatalog } from '#services/file/file_permissions'",
        "import { maintenancePermissionCatalog } from '#services/maintenance/maintenance_permissions'",
        "import { loggingPermissionCatalog } from '#services/logging/logging_permissions'",
        "import type { PermissionSlugs, SlugKeys } from '#types/permissions'",
        '',
        '/**',
        ' * The composed system permission catalog of this flavor: `category →',
        ' * actions` matrix ordered by domain (core, auth, file, maintenance,',
        ' * logging). The permission seeder persists exactly this matrix, so it',
        ' * is the single source of the persisted slugs.',
        ' */',
        'export const permissionCatalog = {',
        '  ...corePermissionCatalog,',
        '  ...authPermissionCatalog,',
        '  ...filePermissionCatalog,',
        '  ...maintenancePermissionCatalog,',
        '  ...loggingPermissionCatalog,',
        '}',
        '',
        '/** Union of every system permission slug in this flavor. */',
        'export type PermissionSlug = PermissionSlugs<typeof permissionCatalog>',
        '',
        '/**',
        ' * The Pascal-Case form of a snake_case permission action (`manage_roles` →',
        ' * `ManageRoles`); the runtime counterpart of the `SlugKey` type.',
        ' */',
        'const slugPart = (part: string): string =>',
        '  part',
        "    .split('_')",
        '    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))',
        "    .join('')",
        '',
        '/**',
        " * The identity map of this flavor's permission slugs: one camelCase key per",
        ' * slug (`usersView`, `usersManageRoles`, ...) whose value is the raw slug',
        ' * string. Derived at runtime from the {@link permissionCatalog}, so renaming',
        ' * a slug in a domain catalog file renames its key here, and every former',
        ' * `permissions.*` use site fails to compile until it is updated.',
        ' */',
        'export const permissions = Object.fromEntries(',
        '  (Object.keys(permissionCatalog) as Array<keyof typeof permissionCatalog>).flatMap(',
        '    (category): Array<[string, string]> =>',
        '      (permissionCatalog[category] as readonly string[]).map(',
        '        (action): [string, string] => [',
        '          `${category}${slugPart(action)}`,',
        '          `${category}.${action}`,',
        '        ],',
        '      ),',
        '  ),',
        ') as Record<SlugKeys<typeof permissionCatalog>, PermissionSlug>',
        '',
        '/**',
        ' * The system role slugs of this flavor; the role seeder persists exactly',
        ' * this list, so it is the single source of the persisted role slugs.',
        ' */',
        'export const systemRoleSlugs = coreRoleSlugs',
        '',
        '/** Union of every system role slug in this flavor. */',
        'export type SystemRoleSlug = (typeof systemRoleSlugs)[number]',
        '',
      ].join('\n'),
    },

    // ─── start/dashboard.ts — drop the page + template collectors ───────────
    {
      path: 'start/dashboard.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Dashboard composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the dashboard section collectors of every domain existing in',
        '| this flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its section disappears from the admin dashboard.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { DashboardRegistry } from '#services/core/dashboard_registry'",
        "import { AuthDashboardCollector } from '#services/auth/auth_dashboard_collector'",
        "import { FileDashboardCollector } from '#services/file/file_dashboard_collector'",
        '',
        'app.container.singleton(DashboardRegistry, () => new DashboardRegistry())',
        '',
        'const registry = await app.container.make(DashboardRegistry)',
        '',
        "registry.register('auth', () => app.container.make(AuthDashboardCollector))",
        "registry.register('file', () => app.container.make(FileDashboardCollector))",
        '',
      ].join('\n'),
    },

    // ─── start/container.ts — drop the builder session binding ──────────────
    {
      path: 'start/container.ts',
      content: [
        "import app from '@adonisjs/core/services/app'",
        "import { BackupEngine } from '#services/backup/backup_engine'",
        "import { CacheService } from '#services/cache/cache_service'",
        "import { RedisCacheDriver } from '#services/cache/drivers/redis_cache_driver'",
        "import { LogService } from '#services/logging/log_service'",
        "import { MaintenanceService } from '#services/maintenance/maintenance_service'",
        '',
        '/**',
        ' * IoC container bindings.',
        ' *',
        ' * Singleton services are instantiated exactly once per process and reused',
        ' * across every request — which is what makes in-flight state (locks,',
        ' * sessions) work correctly without serialising to a database on every call.',
        ' * Factory bindings are re-created on each resolution with runtime arguments',
        ' * supplied via {@link app.container.make}.',
        ' *',
        " * Add this file to `adonisrc.ts` preloads if it isn't already:",
        ' *',
        ' * @example',
        ' * // adonisrc.ts',
        ' * preloads: [',
        " *   () => import('#start/container'),",
        ' * ]',
        ' */',
        '',
        '// ─── BackupEngine (factory) ────────────────────────────────────────────',
        '',
        '/**',
        ' * Factory binding for {@link BackupEngine} so that callers can resolve it',
        ' * through the container instead of using `new`. Runtime arguments',
        ' * (`strategyType`, `tempDir`) are supplied at resolution time which keeps',
        ' * the strategy dynamic while still being mockable in tests via',
        ' * {@link app.container.swap}.',
        ' *',
        ' * @example',
        " * const engine = await app.container.make(BackupEngine, ['full', 'storage/temp/backups'])",
        ' */',
        'app.container.bind(BackupEngine, async (resolver, runtimeValues) => {',
        '  const [strategyType, tempDir] = runtimeValues ?? []',
        '  const logService = await resolver.make(LogService)',
        '  return new BackupEngine(strategyType, tempDir, logService)',
        '})',
        '',
        '// ─── CacheService (singleton) ──────────────────────────────────────────',
        '',
        '/**',
        ' * The root `CacheService` backed by Redis.',
        ' * Inject or resolve via the container anywhere in the app:',
        ' *',
        ' * @example',
        ' * // In a service or controller',
        ' * const cache = await app.container.make(CacheService)',
        ' */',
        'app.container.singleton(CacheService, () => {',
        '  const driver = new RedisCacheDriver()',
        '  return new CacheService(driver)',
        '})',
        '',
        '// ─── MaintenanceService (singleton) ────────────────────────────────────',
        '',
        '/**',
        ' * Maintenance service singleton.',
        ' * Handles Redis + memory fallback for maintenance mode configuration.',
        ' * Initializes memory fallback on first resolution.',
        ' */',
        'app.container.singleton(MaintenanceService, async () => {',
        '  const service = MaintenanceService.getInstance()',
        '  await service.initializeMemoryFallback()',
        '  return service',
        '})',
        '',
      ].join('\n'),
    },

    // ─── start/sitemap.ts — drop the page contributor (routes only) ─────────
    {
      path: 'start/sitemap.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Sitemap composition',
        '|--------------------------------------------------------------------------',
        '|',
        '| Registers the sitemap contributors of every domain existing in this',
        '| flavor of the application. This file is part of the composition set',
        "| that flavor manifests may rewrite: remove a domain's registration and",
        '| its URLs disappear from `sitemap.xml`.',
        '|',
        '| The route collector is always present (hand-written `front.*` routes',
        '| exist in every flavor with a public front). The page collector is',
        '| CMS-specific and is removed by the `inertia` flavor manifest.',
        '|',
        '*/',
        '',
        "import app from '@adonisjs/core/services/app'",
        "import { SitemapRegistry } from '#services/core/sitemap_registry'",
        "import { RouteSitemapCollector } from '#services/core/route_sitemap_collector'",
        '',
        'app.container.singleton(SitemapRegistry, () => new SitemapRegistry())',
        '',
        'const registry = await app.container.make(SitemapRegistry)',
        '',
        "registry.register('routes', () => app.container.make(RouteSitemapCollector))",
        '',
      ].join('\n'),
    },

    // ─── adonisrc.ts — drop the Transmit provider + preload ─────────────────
    {
      path: 'adonisrc.ts',
      content: [
        "import { indexPages } from '@adonisjs/inertia'",
        "import { indexEntities } from '@adonisjs/core'",
        "import { defineConfig } from '@adonisjs/core/app'",
        "import { generateRegistry } from '@tuyau/core/hooks'",
        '',
        'export default defineConfig({',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Experimental flags',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | The following features will be enabled by default in the next major',
        '  | release of AdonisJS. You can opt into them today to avoid any breaking',
        '  | changes during upgrade.',
        '  |',
        '  */',
        '  experimental: {},',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Commands',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of ace commands to register from packages. The application',
        '  | commands will be scanned automatically from the "./commands" directory.',
        '  |',
        '  */',
        '  commands: [',
        "    () => import('@adonisjs/core/commands'),",
        "    () => import('@adonisjs/lucid/commands'),",
        "    () => import('@adonisjs/session/commands'),",
        "    () => import('@adonisjs/inertia/commands'),",
        "    () => import('@adonisjs/mail/commands'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Directories',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  */',
        '  directories: {',
        "    httpControllers: 'app/http/controllers',",
        "    transformers: 'app/data/transformers',",
        "    middleware: 'app/http/middleware',",
        "    services: 'app/domain/services',",
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Service providers',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of service providers to import and register when booting the',
        '  | application',
        '  |',
        '  */',
        '  providers: [',
        "    () => import('@adonisjs/core/providers/app_provider'),",
        "    () => import('@adonisjs/core/providers/hash_provider'),",
        '    {',
        "      file: () => import('@adonisjs/core/providers/repl_provider'),",
        "      environment: ['repl', 'test'],",
        '    },',
        "    () => import('@adonisjs/core/providers/vinejs_provider'),",
        "    () => import('@adonisjs/core/providers/edge_provider'),",
        "    () => import('@adonisjs/session/session_provider'),",
        "    () => import('@adonisjs/vite/vite_provider'),",
        "    () => import('@adonisjs/shield/shield_provider'),",
        "    () => import('@adonisjs/static/static_provider'),",
        "    () => import('@adonisjs/lucid/database_provider'),",
        "    () => import('@adonisjs/cors/cors_provider'),",
        "    () => import('@adonisjs/inertia/inertia_provider'),",
        "    () => import('@adonisjs/auth/auth_provider'),",
        "    () => import('#providers/api_provider'),",
        "    () => import('@adonisjs/redis/redis_provider'),",
        "    () => import('#providers/sentry_provider'),",
        "    () => import('@adonisjs/i18n/i18n_provider'),",
        "    () => import('@adonisjs/ally/ally_provider'),",
        "    () => import('@adonisjs/mail/mail_provider'),",
        "    () => import('@adonisjs/drive/drive_provider'),",
        "    () => import('@adonisjs/limiter/limiter_provider'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Preloads',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of modules to import before starting the application.',
        '  |',
        '  */',
        '  preloads: [',
        "    () => import('#start/routes'),",
        "    () => import('#start/kernel'),",
        "    () => import('#start/validator'),",
        "    () => import('#start/events'),",
        "    () => import('#start/container'),",
        "    () => import('#start/dashboard'),",
        "    () => import('#start/sitemap'),",
        "    () => import('#start/nav'),",
        "    () => import('#start/extensions'),",
        '  ],',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Tests',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | List of test suites to organize tests by their type. Feel free to',
        '  | remove and add additional suites.',
        '  |',
        '  */',
        '  tests: {',
        '    suites: [',
        '      {',
        "        files: ['tests/unit/**/*.spec.{ts,js}'],",
        "        name: 'unit',",
        '        timeout: 2000,',
        '      },',
        '      {',
        "        files: ['tests/integration/**/*.spec.{ts,js}'],",
        "        name: 'integration',",
        '        timeout: 5000,',
        '      },',
        '      {',
        "        files: ['tests/functional/**/*.spec.{ts,js}'],",
        "        name: 'functional',",
        '        timeout: 30000,',
        '      },',
        '      {',
        "        files: ['tests/browser/**/*.spec.{ts,js}'],",
        "        name: 'browser',",
        '        timeout: 300000,',
        '      },',
        '    ],',
        '    forceExit: false,',
        '  },',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Metafiles',
        '  |--------------------------------------------------------------------------',
        '  |',
        '  | A collection of files you want to copy to the build folder when',
        '  | creating the production build.',
        '  |',
        '  */',
        '  metaFiles: [',
        '    {',
        "      pattern: 'resources/views/**/*.edge',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'public/**',",
        '      reloadServer: false,',
        '    },',
        '    {',
        "      pattern: 'resources/lang/**/*.{json,yaml,yml}',",
        '      reloadServer: false,',
        '    },',
        '  ],',
        '',
        '  hooks: {',
        '    init: [',
        '      indexEntities({',
        '        transformers: {',
        '          enabled: true,',
        '          withSharedProps: true,',
        "          source: 'app/data/transformers',",
        "          importAlias: '#transformers',",
        "          glob: ['**\\/*transformer.ts'],",
        '        },',
        '        controllers: {',
        '          enabled: true,',
        "          source: 'app/http/controllers',",
        "          importAlias: '#controllers',",
        "          glob: ['**\\/*_controller.ts'],",
        '        },',
        '      }),',
        "      indexPages({ framework: 'react' }),",
        '      generateRegistry(),',
        '    ],',
        "    buildStarting: [() => import('@adonisjs/vite/build_hook')],",
        '  },',
        '})',
        '',
      ].join('\n'),
    },

    // ─── start/env.ts — drop the CMS content-policy variables ───────────────
    {
      path: 'start/env.ts',
      content: [
        '/*',
        '|--------------------------------------------------------------------------',
        '| Environment variables service',
        '|--------------------------------------------------------------------------',
        '|',
        '| The `Env.create` method creates an instance of the Env service. The',
        '| service validates the environment variables and also cast values',
        '| to JavaScript data types.',
        '|',
        '*/',
        '',
        "import { Env } from '@adonisjs/core/env'",
        '',
        "export default await Env.create(new URL('../', import.meta.url), {",
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring node',
        '  |----------------------------------------------------------',
        '  */',
        "  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),",
        '  PORT: Env.schema.number(),',
        "  HOST: Env.schema.string({ format: 'host' }),",
        '  LOG_LEVEL: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring app',
        '  |----------------------------------------------------------',
        '  */',
        '  APP_KEY: Env.schema.secret(),',
        "  APP_URL: Env.schema.string({ format: 'url', tld: false }),",
        '  APP_NAME: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring session',
        '  |----------------------------------------------------------',
        '  */',
        "  SESSION_DRIVER: Env.schema.enum(['cookie', 'memory', 'database', 'redis'] as const),",
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the auth guards',
        '  |----------------------------------------------------------',
        '  |',
        '  | Which authentication mechanisms are active. full/inertia keep the',
        '  | session guard and may opt into the token guard (REST API); the api',
        '  | flavor disables the session guard entirely.',
        '  |',
        '  */',
        '  AUTH_GUARD_WEB: Env.schema.boolean.optional(),',
        '  AUTH_GUARD_API: Env.schema.boolean.optional(),',
        '  AUTH_API_TOKEN_EXPIRY: Env.schema.string.optional(),',
        '  AUTH_API_CLIENT_URL: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring database connection',
        '  |----------------------------------------------------------',
        '  */',
        "  PG_HOST: Env.schema.string({ format: 'host' }),",
        '  PG_PORT: Env.schema.number(),',
        '  PG_USER: Env.schema.string(),',
        '  PG_PASSWORD: Env.schema.secret(),',
        '  PG_DB_NAME: Env.schema.string(),',
        '',
        '  /*',
        '  |--------------------------------------------------------------------------',
        '  | Variables for configuring @adonisjs/redis package',
        '  |--------------------------------------------------------------------------',
        '  */',
        "  REDIS_HOST: Env.schema.string({ format: 'host' }),",
        '  REDIS_PORT: Env.schema.number(),',
        '  REDIS_PASSWORD: Env.schema.string.optional(),',
        '  REDIS_SOCKET: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the mail package',
        '  |----------------------------------------------------------',
        '  */',
        "  MAIL_MAILER: Env.schema.enum(['smtp'] as const),",
        '  MAIL_FROM_NAME: Env.schema.string(),',
        '  MAIL_FROM_ADDRESS: Env.schema.string(),',
        '  SMTP_HOST: Env.schema.string(),',
        '  SMTP_PORT: Env.schema.number(),',
        '  SMTP_USERNAME: Env.schema.string(),',
        '  SMTP_PASSWORD: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the Sentry SDK',
        '  |----------------------------------------------------------',
        '  */',
        '  SENTRY_DSN: Env.schema.string(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration',
        '  |----------------------------------------------------------',
        '  */',
        "  BACKUP_STORAGE_DISK: Env.schema.enum.optional(['fs', 's3', 'r2'] as const),",
        '  BACKUP_TIME: Env.schema.string.optional(),',
        '  BACKUP_ENCRYPTION_ENABLED: Env.schema.boolean.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Retention',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_RETENTION_DAILY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_WEEKLY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_MONTHLY: Env.schema.number.optional(),',
        '  BACKUP_RETENTION_YEARLY: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Health Check',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_MAX_AGE_HOURS: Env.schema.number.optional(),',
        '  BACKUP_MAX_SIZE_MB: Env.schema.number.optional(),',
        '  BACKUP_MIN_FREE_SPACE_GB: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Notifications',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_NOTIFICATION_EMAIL: Env.schema.string.optional(),',
        '  BACKUP_NOTIFY_SUCCESS: Env.schema.boolean.optional(),',
        '  BACKUP_NOTIFY_FAILURE: Env.schema.boolean.optional(),',
        '  BACKUP_NOTIFY_HEALTH_CHECK: Env.schema.boolean.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for Backup Configuration: Differential',
        '  |----------------------------------------------------------',
        '  */',
        '  BACKUP_EXCLUDED_TABLES: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the drive package',
        '  |----------------------------------------------------------',
        '  */',
        "  DRIVE_DISK: Env.schema.enum(['fs', 's3', 'r2'] as const),",
        '  AWS_ACCESS_KEY_ID: Env.schema.string.optional(),',
        '  AWS_SECRET_ACCESS_KEY: Env.schema.string.optional(),',
        '  AWS_REGION: Env.schema.string.optional(),',
        '  S3_BUCKET: Env.schema.string.optional(),',
        '  R2_KEY: Env.schema.string.optional(),',
        '  R2_SECRET: Env.schema.string.optional(),',
        '  R2_BUCKET: Env.schema.string.optional(),',
        '  R2_ENDPOINT: Env.schema.string.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring file upload',
        '  |----------------------------------------------------------',
        '  */',
        '  MAX_UPLOAD_SIZE: Env.schema.number.optional(),',
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for configuring the limiter package',
        '  |----------------------------------------------------------',
        '  */',
        "  LIMITER_STORE: Env.schema.enum(['redis', 'memory'] as const),",
        '',
        '  /*',
        '  |----------------------------------------------------------',
        '  | Variables for sitemap.xml generation.',
        '  | Comma-separated lists; both have safe defaults in config/sitemap.ts.',
        '  |----------------------------------------------------------',
        '  */',
        '  SITEMAP_ADDITIONS: Env.schema.string.optional(),',
        '  SITEMAP_EXCLUSIONS: Env.schema.string.optional(),',
        '})',
        '',
      ].join('\n'),
    },

    // ─── .env.example — drop the CMS content-policy variables ───────────────
    {
      path: '.env.example',
      content: [
        '# Node',
        'TZ=UTC',
        'PORT=3333',
        'HOST=localhost',
        'NODE_ENV=development',
        '',
        '# App',
        'LOG_LEVEL=info',
        'APP_KEY=',
        'APP_URL=http://localhost:3333',
        'APP_NAME=AdonisJS Foundry',
        '',
        '# Session',
        'SESSION_DRIVER=redis',
        '',
        '# Auth guards — which authentication mechanisms are active.',
        '# full/inertia: keep AUTH_GUARD_API unset (session only), set it to true to',
        '# also expose the token-guarded REST API (/api/v1/*) e.g. for a mobile app.',
        '# api flavor: AUTH_GUARD_WEB=false + AUTH_GUARD_API=true (no session guard).',
        'AUTH_GUARD_WEB=true',
        'AUTH_GUARD_API=false',
        '# Default lifetime of issued API tokens (e.g. "30 days", "7d", "24h").',
        'AUTH_API_TOKEN_EXPIRY=30 days',
        '# Reserved for a future OAuth API mode (redirecting non-browser clients after',
        '# a provider callback). Declared so deployments can set it, but not read yet —',
        '# mobile clients complete OAuth in a system browser, then use /api/v1/auth/login.',
        'AUTH_API_CLIENT_URL=',
        '',
        '# Database',
        'PG_HOST=127.0.0.1',
        'PG_PORT=5432',
        'PG_USER=user',
        'PG_PASSWORD=password',
        'PG_DB_NAME=app',
        '',
        '# Redis',
        'REDIS_HOST=127.0.0.1',
        'REDIS_PORT=6379',
        'REDIS_PASSWORD=',
        'REDIS_SOCKET=',
        '',
        '# Mail',
        'MAIL_MAILER=smtp',
        'MAIL_FROM_NAME=${APP_NAME}',
        'MAIL_FROM_ADDRESS=contact@example.com',
        '',
        '# SMTP',
        'SMTP_HOST=localhost',
        'SMTP_PORT=1025',
        'SMTP_USERNAME=username',
        'SMTP_PASSWORD=password',
        '',
        '# Sentry',
        'SENTRY_DSN=<your_dsn_url>',
        '',
        '# Oauth',
        'FACEBOOK_CLIENT_ID=',
        'FACEBOOK_CLIENT_SECRET=',
        'GITHUB_CLIENT_ID=',
        'GITHUB_CLIENT_SECRET=',
        'GOOGLE_CLIENT_ID=',
        'GOOGLE_CLIENT_SECRET=',
        'DRIVE_DISK=fs',
        'AWS_ACCESS_KEY_ID=',
        'AWS_SECRET_ACCESS_KEY=',
        'AWS_REGION=',
        'S3_BUCKET=',
        'R2_KEY=',
        'R2_SECRET=',
        'R2_BUCKET=',
        'R2_ENDPOINT=',
        'LIMITER_STORE=redis',
        '# Sitemap — comma-separated additions (absolute or root-relative URLs) and exclusions (route names, paths, or absolute URLs)',
        'SITEMAP_ADDITIONS=',
        'SITEMAP_EXCLUSIONS=',
        '',
      ].join('\n'),
    },

    // ─── README.md — flavor-specific rewrite (conventions + upgrade path) ───
    {
      path: 'README.md',
      content: [
        '# AdonisJS Foundry — `inertia` flavor',
        '',
        'A production-ready AdonisJS v7 boilerplate with a hand-written Inertia.js + React',
        'front and a full admin back-office — without the dynamic page CMS, visual',
        'builder, or template system. This flavor is for projects that want a solid',
        'auth + admin foundation and their own hand-crafted pages.',
        '',
        '## What is included',
        '',
        '- **Admin back-office** — dashboard, users, roles, permissions, files, logs,',
        '  maintenance, settings (profile, account, preferences).',
        '- **Full auth flow** — registration, login, logout, email verification, password',
        '  reset, OAuth (GitHub, Google, Facebook), invitations, define-password.',
        '- **File management** — upload, folders, multi-disk storage (local, S3, R2),',
        '  image optimization, and server-side file resolution for hand-written pages.',
        '- **SEO** — dynamic `sitemap.xml` and `robots.txt`. Every `front.*` route is',
        '  collected automatically.',
        '- **Minimal front shell** — a blank home page and error pages, each served by',
        '  its own controller.',
        '',
        'Explicitly **not** included: the page domain, template domain, and the Transmit',
        'real-time integration (page builder only).',
        '',
        '## Conventions',
        '',
        'The flavor is self-documenting by construction — the files you open first are',
        'the pattern to follow:',
        '',
        '- **One controller per page.** Each public page is served by a dedicated',
        '  controller in the `core` domain (`app/http/controllers/core/front/`), keeping',
        '  the controller thin and delegating to services.',
        '- **`front.*` route names.** Public routes are declared manually in',
        '  `start/routes/front.routes.ts` via `registerFrontRoutes()` and named',
        '  `front.home`, `front.about`, ... so the sitemap collector and your frontend',
        '  links reference them consistently.',
        '- **Hand-written Inertia pages.** Front pages live under',
        '  `inertia/pages/core/front/` and use the public layout; error pages under',
        '  `inertia/pages/errors/`.',
        '- **i18n.** Each page resolves its labels from an `en`/`fr` namespace',
        '  (`resources/lang/{en,fr}/home.json`) and renders through `useTranslation`',
        '  — see `inertia/pages/core/front/home.tsx`.',
        '- **Media library in your pages.** Resolve files on the server with the',
        '  `FindFileAction` and render them with `<FileImage>` instead of hand-building',
        '  storage URLs.',
        '- **Data-driven dashboard.** The admin dashboard renders exactly the sections',
        '  present in the payload; the kept domains (users, files) register their cards',
        '  in the client-side section registry.',
        '',
        '## Quick start',
        '',
        '```bash',
        'npm install',
        'cp .env.example .env',
        'node ace generate:key',
        'node ace migration:run',
        'npm run dev',
        '```',
        '',
        'The app is available at `http://localhost:3333`. The admin is at `/admin`.',
        '',
        '## Upgrade path to `full`',
        '',
        'Choosing this flavor is not a one-way door. See',
        '`docs/flavors/inertia/upgrade-to-full.md` for the documented manual path to',
        'recover the CMS, the builder, and Transmit later.',
        '',
        '## Available scripts',
        '',
        '| Script              | Description                     |',
        '| ------------------- | ------------------------------- |',
        '| `npm run dev`       | Start the dev server with HMR   |',
        '| `npm run build`     | Build for production            |',
        '| `npm start`         | Start the production server     |',
        '| `npm test`          | Run tests (Japa)                |',
        '| `npm run lint`      | Run ESLint                      |',
        '| `npm run format`    | Format code with Prettier       |',
        '| `npm run typecheck` | Type-check backend and frontend |',
        '',
      ].join('\n'),
    },
  ],

  dependencies: {
    packages: ['@adonisjs/transmit', '@adonisjs/transmit-client'],
  },
}

export default inertiaManifest
