/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class PermissionSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'description',
    'id',
    'isSystem',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = PermissionSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionId: number
  @column()
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'isSystem',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TokenSchema extends BaseModel {
  static $columns = [
    'attempts',
    'createdAt',
    'expiresAt',
    'id',
    'selector',
    'token',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = TokenSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare selector: string | null
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'emailVerifiedAt',
    'facebookId',
    'githubId',
    'googleId',
    'id',
    'locale',
    'password',
    'pendingEmail',
    'roleId',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare facebookId: string | null
  @column()
  declare githubId: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare pendingEmail: string | null
  @column()
  declare roleId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
