/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type DashboardTransformer from '#transformers/dashboard_transformer'
import type FileFolderTransformer from '#transformers/file_folder_transformer'
import type FileTransformer from '#transformers/file_transformer'
import type LogEntryTransformer from '#transformers/log_entry_transformer'
import type PagePageRevisionTransformer from '#transformers/page/page_revision_transformer'
import type PagePageTransformer from '#transformers/page/page_transformer'
import type PagePageTranslationTransformer from '#transformers/page/page_translation_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type TemplateTemplateTransformer from '#transformers/template/template_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Dashboard = InferData<DashboardTransformer>
  export namespace Dashboard {
    export type Variants = InferVariants<DashboardTransformer>
  }
  export type FileFolder = InferData<FileFolderTransformer>
  export namespace FileFolder {
    export type Variants = InferVariants<FileFolderTransformer>
  }
  export type File = InferData<FileTransformer>
  export namespace File {
    export type Variants = InferVariants<FileTransformer>
  }
  export type LogEntry = InferData<LogEntryTransformer>
  export namespace LogEntry {
    export type Variants = InferVariants<LogEntryTransformer>
  }
  export namespace Page {
    export type PageRevision = InferData<PagePageRevisionTransformer>
    export namespace PageRevision {
      export type Variants = InferVariants<PagePageRevisionTransformer>
    }
    export type Page = InferData<PagePageTransformer>
    export namespace Page {
      export type Variants = InferVariants<PagePageTransformer>
    }
    export type PageTranslation = InferData<PagePageTranslationTransformer>
    export namespace PageTranslation {
      export type Variants = InferVariants<PagePageTranslationTransformer>
    }
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export namespace Template {
    export type Template = InferData<TemplateTemplateTransformer>
    export namespace Template {
      export type Variants = InferVariants<TemplateTemplateTransformer>
    }
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
